// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DiagnosticCheck 描述一项实测结果；Status 使用 pass、warning 或 fail。
 * 平台缺少隔离能力属于 warning，不应伪装成已经验证了原生隔离。
 */
export class DiagnosticCheck {
    /**
     * Creates a new DiagnosticCheck instance.
     * @param {Partial<DiagnosticCheck>} [$$source = {}] - The source object to create the DiagnosticCheck.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("detail" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["detail"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DiagnosticCheck instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DiagnosticCheck}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DiagnosticCheck(/** @type {Partial<DiagnosticCheck>} */($$parsedSource));
    }
}

/**
 * Diagnostics 汇总自检结果，fail 优先于 warning，全部检查通过才为 pass。
 */
export class Diagnostics {
    /**
     * Creates a new Diagnostics instance.
     * @param {Partial<Diagnostics>} [$$source = {}] - The source object to create the Diagnostics.
     */
    constructor($$source = {}) {
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("checks" in $$source)) {
            /**
             * @member
             * @type {DiagnosticCheck[]}
             */
            this["checks"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Diagnostics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Diagnostics}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("checks" in $$parsedSource) {
            $$parsedSource["checks"] = $$createField1_0($$parsedSource["checks"]);
        }
        return new Diagnostics(/** @type {Partial<Diagnostics>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DiagnosticCheck.createFrom;
const $$createType1 = $Create.Array($$createType0);
