// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AgentService 是 Agent Domain Service 的 Wails Adapter。
 * 
 * 文件夹选择也放在这里，是因为 Native Dialog 属于 Desktop Adapter，
 * 不应该进入 workspace 或 agents Domain Package。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateAgent 创建 Agent。
 * @param {$models.CreateAgentRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function CreateAgent(request) {
    return $Call.ByID(3667126956, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteAgent 删除 Agent Profile。
 * 
 * Workspace 文件不会被自动删除。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteAgent(id) {
    return $Call.ByID(4076039157, id);
}

/**
 * GetAgent 返回指定 Agent。
 * @param {string} id
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function GetAgent(id) {
    return $Call.ByID(3627367090, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSandboxStatus 返回当前平台能力探测结果，不触发任何子进程。
 * @returns {$CancellablePromise<$models.SandboxStatusDTO>}
 */
export function GetSandboxStatus() {
    return $Call.ByID(3963892442).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListAgents 返回全部 Agent。
 * @returns {$CancellablePromise<$models.AgentDTO[]>}
 */
export function ListAgents() {
    return $Call.ByID(307178989).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListBuiltinTools 返回当前 Registry 中可供 Agent 选择的 Builtin Tool。
 * @returns {$CancellablePromise<$models.BuiltinToolDTO[]>}
 */
export function ListBuiltinTools() {
    return $Call.ByID(3268878825).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * RunSandboxDiagnostics 在临时目录中验证 PathGuard，并在平台支持时实际验证原生文件系统隔离。
 * 自检不会读取用户文件，也不会修改 Workspace；所有探针文件都位于 OS 临时目录。
 * @returns {$CancellablePromise<$models.SandboxDiagnosticsDTO>}
 */
export function RunSandboxDiagnostics() {
    return $Call.ByID(4285542541).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectSandboxDirectory 打开原生目录选择器，用于 Additional Read/Write Path。
 * @param {string} currentPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectSandboxDirectory(currentPath) {
    return $Call.ByID(2050441857, currentPath);
}

/**
 * SelectWorkspaceDirectory 打开系统原生目录选择器。
 * 
 * currentPath 只用于指定 Dialog 初始目录。
 * 即使该参数来自前端，也绝不会被直接当作 Agent Workspace 保存；
 * 真正保存前仍然会经过 WorkspaceManager.Validate。
 * 
 * 用户取消时返回空字符串。
 * @param {string} currentPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectWorkspaceDirectory(currentPath) {
    return $Call.ByID(1593903647, currentPath);
}

/**
 * SetAgentModel 只修改 Agent 默认模型。
 * @param {string} id
 * @param {$models.AgentModelRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function SetAgentModel(id, request) {
    return $Call.ByID(1797889555, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetAgentSkills 只修改 Agent Skill 选择。
 * @param {string} id
 * @param {$models.AgentSkillsRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function SetAgentSkills(id, request) {
    return $Call.ByID(1481834340, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateAgent 修改 Agent。
 * @param {string} id
 * @param {$models.UpdateAgentRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function UpdateAgent(id, request) {
    return $Call.ByID(2371529083, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateAgentProfile 只修改 Agent 名称与 Instruction。
 * @param {string} id
 * @param {$models.AgentProfileRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function UpdateAgentProfile(id, request) {
    return $Call.ByID(2639888100, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateAgentSecurity 显式替换 Agent Builtin Tool 与 Sandbox 配置。
 * @param {string} id
 * @param {$models.AgentSecurityRequest} request
 * @returns {$CancellablePromise<$models.AgentDTO>}
 */
export function UpdateAgentSecurity(id, request) {
    return $Call.ByID(3782335613, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateSandboxSettings 持久化应用级 Sandbox 默认策略，并立即更新当前进程中的 Manager。
 * 已经开始的 Runtime Turn 使用冻结的 EffectivePolicy，不会被设置页中途改变。
 * @param {$models.SandboxSettingsRequest} request
 * @returns {$CancellablePromise<$models.SandboxStatusDTO>}
 */
export function UpdateSandboxSettings(request) {
    return $Call.ByID(3325658948, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.AgentDTO.createFrom;
const $$createType1 = $models.SandboxStatusDTO.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.BuiltinToolDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.SandboxDiagnosticsDTO.createFrom;
