// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService 是 Wails Desktop 暴露给 Vue 的最小应用服务。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as databackup$0 from "../databackup/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<void>}
 */
export function CancelPendingBackup() {
    return $Call.ByID(3079515720);
}

/**
 * ExportBackup 仅安排下次启动前的离线加密备份，确保跨文件快照一致。
 * @param {string} passphrase
 * @returns {$CancellablePromise<string>}
 */
export function ExportBackup(passphrase) {
    return $Call.ByID(3047856093, passphrase);
}

/**
 * @returns {$CancellablePromise<databackup$0.BackupStatus>}
 */
export function PendingBackupStatus() {
    return $Call.ByID(921845544).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ScheduleRestore 验证用户选择的备份，下次启动时在 Core 初始化前恢复。
 * @param {string} passphrase
 * @returns {$CancellablePromise<string>}
 */
export function ScheduleRestore(passphrase) {
    return $Call.ByID(3354092834, passphrase);
}

/**
 * Status 返回 Humbert 当前运行状态。
 * @returns {$CancellablePromise<$models.AppStatus>}
 */
export function Status() {
    return $Call.ByID(1184375283).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = databackup$0.BackupStatus.createFrom;
const $$createType1 = $models.AppStatus.createFrom;
