// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService 是 RuntimeService 的 Desktop Adapter。
 * 
 * 调用方向：
 * 
 * 	Vue
 * 	  ↓
 * 	Wails Binding
 * 	  ↓
 * 	ChatService
 * 	  ↓
 * 	RuntimeService
 * 
 * 流式输出方向：
 * 
 * 	RuntimeService
 * 	  ↓
 * 	Internal EventBus
 * 	  ↓
 * 	ChatService Event Bridge
 * 	  ↓
 * 	Wails Custom Event
 * 	  ↓
 * 	Vue Events.On()
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contextengine$0 from "../contextengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as runtime$0 from "../runtime/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelTurn 请求取消指定 Turn。
 * @param {string} requestID
 * @returns {$CancellablePromise<void>}
 */
export function CancelTurn(requestID) {
    return $Call.ByID(4271645435, requestID);
}

/**
 * CompactContext 执行用户主动压缩。
 * 
 * updateMemory=false 对应“压缩”，只提交 CompactionEntry；true 对应“压缩并更新”，在
 * Compaction 后额外强制刷新当前 Session memory.json。运行中的 Session 会返回
 * runtime.ErrSessionBusy，避免对活动 ReAct loop 的历史进行并发改写。
 * @param {string} sessionID
 * @param {boolean} updateMemory
 * @returns {$CancellablePromise<runtime$0.ManualCompactionResult>}
 */
export function CompactContext(sessionID, updateMemory) {
    return $Call.ByID(215656890, sessionID, updateMemory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ContextOverview 返回 Context Usage 与统一 Runtime Manifest。
 * 
 * 前端使用该接口展示“下一 Turn 实际会加载什么”，避免分别读取 Agent、Skill、MCP、Sandbox
 * 后自行拼接状态。该调用不会发起 Provider 请求，也不会连接 MCP Server。
 * @param {string} sessionID
 * @returns {$CancellablePromise<runtime$0.ContextOverview>}
 */
export function ContextOverview(sessionID) {
    return $Call.ByID(2758503998, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ContextStatus 返回 Composer 展示所需的 Context Usage。
 * 
 * 该方法不触发模型调用或压缩，只读取当前 Session、Model、Tool Schema 与派生 Memory。
 * 返回值中的 UsedTokens 是本地保守估算，ContextWindow 来自用户维护的 Model 配置。
 * @param {string} sessionID
 * @returns {$CancellablePromise<contextengine$0.Usage>}
 */
export function ContextStatus(sessionID) {
    return $Call.ByID(756400219, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ResolveApproval 处理当前等待中的 Human Approval，并异步恢复原 User Turn。
 * 
 * 该 Wails 调用只等待 Permission Rule（如果选择了 Session/Agent 授权）提交完成，不等待
 * Tool 或后续模型回复。真实执行结果继续通过 humbert:runtime:event 返回，因此前端按钮不会
 * 被长时间模型调用阻塞。
 * @param {$models.ResolveApprovalRequest} request
 * @returns {$CancellablePromise<runtime$0.ResolveApprovalResult>}
 */
export function ResolveApproval(request) {
    return $Call.ByID(1605464965, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * StartTurn 发起一个新的异步 User Turn。
 * 
 * 方法只等待 Runtime 完成 Snapshot/Message/Run 初始化，
 * 不等待模型完整回复。
 * @param {$models.StartTurnRequest} request
 * @returns {$CancellablePromise<runtime$0.StartTurnResult>}
 */
export function StartTurn(request) {
    return $Call.ByID(110343861, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = runtime$0.ManualCompactionResult.createFrom;
const $$createType1 = runtime$0.ContextOverview.createFrom;
const $$createType2 = contextengine$0.Usage.createFrom;
const $$createType3 = runtime$0.ResolveApprovalResult.createFrom;
const $$createType4 = runtime$0.StartTurnResult.createFrom;
