// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService 暴露 MCP 控制面 API。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {$models.MCPServerRequest} request
 * @returns {$CancellablePromise<$models.MCPServerDTO>}
 */
export function CreateServer(request) {
    return $Call.ByID(3340483121, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteServer(id) {
    return $Call.ByID(3954876714, id);
}

/**
 * DisconnectServer 主动释放 MCP Session，不修改任何持久化配置。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DisconnectServer(id) {
    return $Call.ByID(4283897383, id);
}

/**
 * DiscoverTools 返回 Server 当前真实 tools/list；它不会自动修改任何 Agent 配置。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MCPToolDTO[]>}
 */
export function DiscoverTools(serverID) {
    return $Call.ByID(3056653772, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ExportServersConfig 导出不包含 Secret 的可移植 MCP 配置 JSON。
 * @returns {$CancellablePromise<string>}
 */
export function ExportServersConfig() {
    return $Call.ByID(1959378790);
}

/**
 * GetAgentTools 返回指定 Agent 当前持久化的 MCP Tool Selection。
 * 连接器 UI 只读取 Agent Profile 这一份事实来源，不在 MCP Server 侧维护反向引用。
 * @param {string} agentID
 * @returns {$CancellablePromise<$models.MCPToolSelectionDTO[]>}
 */
export function GetAgentTools(agentID) {
    return $Call.ByID(947998866, agentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ImportServersConfig 导入 Humbert 非敏感 MCP 配置。为防止缺失 Secret 的配置立即进入
 * Runtime，所有导入 Server 都默认 disabled；CredentialHints 仅用于提醒用户重新填写。
 * @param {string} payload
 * @returns {$CancellablePromise<$models.MCPServerDTO[]>}
 */
export function ImportServersConfig(payload) {
    return $Call.ByID(2817374663, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.MCPServerDTO[]>}
 */
export function ListServers() {
    return $Call.ByID(38048574).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RefreshTools 强制跳过控制面 Catalog 缓存执行真实 tools/list。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MCPToolDTO[]>}
 */
export function RefreshTools(serverID) {
    return $Call.ByID(2713435080, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SetAgentTools 是“连接器”页面保存 Tool 开关的唯一入口。
 * @param {string} agentID
 * @param {$models.MCPToolSelectionDTO[]} selections
 * @returns {$CancellablePromise<void>}
 */
export function SetAgentTools(agentID, selections) {
    return $Call.ByID(4193111430, agentID, selections);
}

/**
 * SetServerEnabled 只切换 MCP Server 控制面状态；Agent Tool Selection 与 Credential 保留。
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<$models.MCPServerDTO>}
 */
export function SetServerEnabled(id, enabled) {
    return $Call.ByID(1649021438, id, enabled).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetToolRisk 保存用户对一个 MCP Tool 的 Humbert Risk Override。
 * Server annotation 只是参考；真正进入 PermissionEngine 的 Risk 只来自这里的显式用户选择。
 * @param {string} serverID
 * @param {string} rawToolName
 * @param {string} risk
 * @returns {$CancellablePromise<void>}
 */
export function SetToolRisk(serverID, rawToolName, risk) {
    return $Call.ByID(1540063375, serverID, rawToolName, risk);
}

/**
 * TestConnection 使用与 Runtime 完全相同的 Session Backend 测试连接。
 * @param {string} serverID
 * @returns {$CancellablePromise<$models.MCPConnectionTestDTO>}
 */
export function TestConnection(serverID) {
    return $Call.ByID(743825638, serverID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @param {$models.MCPServerRequest} request
 * @returns {$CancellablePromise<$models.MCPServerDTO>}
 */
export function UpdateServer(id, request) {
    return $Call.ByID(3485722872, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.MCPServerDTO.createFrom;
const $$createType1 = $models.MCPToolDTO.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.MCPToolSelectionDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($$createType0);
const $$createType6 = $models.MCPConnectionTestDTO.createFrom;
