// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ModelService 是 Model Registry 的 Wails Adapter。
 * 
 * 所有真正业务逻辑位于 models.Registry，
 * 这里仅负责 DTO 转换与 Wails 调用超时。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateModel 创建 Model。
 * @param {$models.SaveModelRequest} request
 * @returns {$CancellablePromise<$models.ModelDTO>}
 */
export function CreateModel(request) {
    return $Call.ByID(1454791668, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * CreateProvider 创建 Provider。
 * @param {$models.CreateProviderRequest} request
 * @returns {$CancellablePromise<$models.ProviderDTO>}
 */
export function CreateProvider(request) {
    return $Call.ByID(2755596358, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteModel 删除不再被当前 Agent 任一模型角色引用的模型。
 * 历史 Session 不阻止删除模型配置。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModel(id) {
    return $Call.ByID(1255579641, id);
}

/**
 * DeleteProvider 删除 Provider。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProvider(id) {
    return $Call.ByID(1382606137, id);
}

/**
 * DiagnoseModel 发送最小请求，并把常见连接故障转换成可处理的提示。
 * @param {string} id
 * @returns {$CancellablePromise<$models.ModelDiagnostic>}
 */
export function DiagnoseModel(id) {
    return $Call.ByID(3159820460, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * State 返回 Provider + Model 完整状态。
 * @returns {$CancellablePromise<$models.ModelSettingsState>}
 */
export function State() {
    return $Call.ByID(3745089920).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * TestModel 发起一次真实模型 API 请求。
 * @param {string} id
 * @returns {$CancellablePromise<$models.TestModelResponse>}
 */
export function TestModel(id) {
    return $Call.ByID(1572021496, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * UpdateModel 修改 Model。
 * @param {string} id
 * @param {$models.SaveModelRequest} request
 * @returns {$CancellablePromise<$models.ModelDTO>}
 */
export function UpdateModel(id, request) {
    return $Call.ByID(3851995243, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateMultimediaConfig 修改应用级多媒体模型路由。
 * @param {$models.MultimediaConfigDTO} request
 * @returns {$CancellablePromise<$models.MultimediaConfigDTO>}
 */
export function UpdateMultimediaConfig(request) {
    return $Call.ByID(1381143563, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * UpdateProvider 修改 Provider。
 * @param {string} id
 * @param {$models.UpdateProviderRequest} request
 * @returns {$CancellablePromise<$models.ProviderDTO>}
 */
export function UpdateProvider(id, request) {
    return $Call.ByID(419214619, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ModelDTO.createFrom;
const $$createType1 = $models.ProviderDTO.createFrom;
const $$createType2 = $models.ModelDiagnostic.createFrom;
const $$createType3 = $models.ModelSettingsState.createFrom;
const $$createType4 = $models.TestModelResponse.createFrom;
const $$createType5 = $models.MultimediaConfigDTO.createFrom;
