// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PermissionService 是 Permission Domain 的 Wails Desktop Adapter。
 * 
 * PermissionEngine 保持与桌面框架无关；本 Service 只负责 DTO 投影、Viper 配置更新和设置页
 * 管理。持久化 Rule 仍由 permission.Store 原子提交，Session Rule 仍由 Engine 内存管理。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearPersistentAllows 撤销所有 Agent Scope 长期 Allow Rule，但保留显式 Deny。
 * 
 * 这是设置页的“恢复谨慎模式”入口。保留 Deny 可以避免用户为了收紧权限创建的安全规则
 * 被一次批量撤销操作意外删除。
 * @returns {$CancellablePromise<number>}
 */
export function ClearPersistentAllows() {
    return $Call.ByID(1042117463);
}

/**
 * ClearSessionRules 清除当前 Session 的全部临时授权。
 * @param {string} sessionID
 * @returns {$CancellablePromise<void>}
 */
export function ClearSessionRules(sessionID) {
    return $Call.ByID(829008335, sessionID);
}

/**
 * DeleteRule 撤销一个 Agent Scope 长期 Rule。
 * 
 * 删除只影响后续 Tool 调用；已经获批并开始 Resume 的调用仍使用 checkpoint 中被冻结的
 * 决策，不会在 Tool 执行一半时被设置页撤销。
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteRule(ruleID) {
    return $Call.ByID(4266607886, ruleID);
}

/**
 * DeleteSessionRule 撤销当前进程中指定 Session 的一条临时 Rule。
 * @param {string} sessionID
 * @param {string} ruleID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSessionRule(sessionID, ruleID) {
    return $Call.ByID(2357628866, sessionID, ruleID);
}

/**
 * State 返回当前默认 Policy、持久化 Agent Rule 以及指定 Session 的临时 Rule。
 * 
 * sessionID 可以为空，此时 SessionRules 返回空列表。这样设置页即使没有打开会话，也仍然
 * 可以管理应用默认策略与长期规则，而不会泄露其他 Session 的临时授权。
 * @param {string} sessionID
 * @returns {$CancellablePromise<$models.PermissionStateDTO>}
 */
export function State(sessionID) {
    return $Call.ByID(975662372, sessionID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * UpdateSettings 使用 Viper 更新 config.yaml，并让 PermissionEngine 与 ApprovalManager 在当前
 * 进程立即采用新配置。
 * 
 * 已经 Pending 的 Approval 保留创建时的 ExpiresAt；新超时只作用于后续审批。已有长期或
 * Session Rule 也不被默认策略修改覆盖，因为它们本来就比默认 Risk Policy 优先。
 * @param {$models.UpdatePermissionSettingsRequest} request
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSettings(request) {
    return $Call.ByID(3525193559, request);
}

// Private type creation functions
const $$createType0 = $models.PermissionStateDTO.createFrom;
