// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preferences$0 from "../preferences/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} text
 * @returns {$CancellablePromise<preferences$0.PersonalMemory>}
 */
export function AddPersonalMemory(text) {
    return $Call.ByID(4294939339, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} text
 * @param {string} sessionID
 * @param {string} entryID
 * @returns {$CancellablePromise<preferences$0.PersonalMemory>}
 */
export function AddPersonalMemoryFromMessage(text, sessionID, entryID) {
    return $Call.ByID(1372226502, text, sessionID, entryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeletePersonalMemory(id) {
    return $Call.ByID(1811549377, id);
}

/**
 * @returns {$CancellablePromise<$models.UserProfileDTO>}
 */
export function GetUserProfile() {
    return $Call.ByID(39164661).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListPersonalMemories 返回用户可查看、修订和遗忘的跨会话事实。
 * @returns {$CancellablePromise<preferences$0.PersonalMemory[]>}
 */
export function ListPersonalMemories() {
    return $Call.ByID(2666718582).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @param {string} text
 * @returns {$CancellablePromise<preferences$0.PersonalMemory>}
 */
export function UpdatePersonalMemory(id, text) {
    return $Call.ByID(4055186371, id, text).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {$models.UserProfileDTO} request
 * @returns {$CancellablePromise<$models.UserProfileDTO>}
 */
export function UpdateUserProfile(request) {
    return $Call.ByID(4209904492, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = preferences$0.PersonalMemory.createFrom;
const $$createType1 = $models.UserProfileDTO.createFrom;
const $$createType2 = $Create.Array($$createType0);
