// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as notifications$0 from "../notifications/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proactive$0 from "../proactive/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.ProactiveSettingsDTO>}
 */
export function GetSettings() {
    return $Call.ByID(4194746984).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<notifications$0.Notification[]>}
 */
export function Notifications(limit) {
    return $Call.ByID(1961544485, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {number} limit
 * @returns {$CancellablePromise<proactive$0.Record[]>}
 */
export function Records(limit) {
    return $Call.ByID(635187323, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function RunHeartbeat() {
    return $Call.ByID(145031076);
}

/**
 * @returns {$CancellablePromise<$models.ProactiveStatusDTO>}
 */
export function Status() {
    return $Call.ByID(1398185917).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.ProactiveSettingsDTO} value
 * @returns {$CancellablePromise<$models.ProactiveSettingsDTO>}
 */
export function UpdateSettings(value) {
    return $Call.ByID(1836083567, value).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProactiveSettingsDTO.createFrom;
const $$createType1 = notifications$0.Notification.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = proactive$0.Record.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ProactiveStatusDTO.createFrom;
