// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CreateProject 以当前产品的一对一默认关系创建 Project + Agent。
 * 领域对象已经分离，未来允许一个 Agent 服务多个 Project 时无需改 Session/Runtime 协议。
 * @param {$models.CreateProjectRequest} request
 * @returns {$CancellablePromise<$models.ProjectDTO>}
 */
export function CreateProject(request) {
    return $Call.ByID(3815116948, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProject(id) {
    return $Call.ByID(891078129, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.ProjectDTO>}
 */
export function GetProject(id) {
    return $Call.ByID(167341746, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.ProjectDTO[]>}
 */
export function ListProjects() {
    return $Call.ByID(2240005381).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} currentPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectWorkspaceDirectory(currentPath) {
    return $Call.ByID(4288249279, currentPath);
}

/**
 * UpdateProject 将一次“项目设置保存”拆成明确领域命令；不再调用全量 UpdateAgent。
 * @param {string} id
 * @param {$models.UpdateProjectRequest} request
 * @returns {$CancellablePromise<$models.ProjectDTO>}
 */
export function UpdateProject(id, request) {
    return $Call.ByID(1750958063, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProjectDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
