// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService 是 Session Domain 的 Wails Adapter。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 创建新 Session。
 * @param {string} agentID
 * @param {string} title
 * @returns {$CancellablePromise<$models.SessionDTO>}
 */
export function Create(agentID, title) {
    return $Call.ByID(1058013738, agentID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete 删除 Session 与完整消息历史。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(373526041, id);
}

/**
 * List 返回 Agent 的 Sessions。
 * @param {string} agentID
 * @returns {$CancellablePromise<$models.SessionDTO[]>}
 */
export function List(agentID) {
    return $Call.ByID(3883780506, agentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * MessagePage 返回 beforeEntryID 之前的一页消息，不依赖生成的 Wails Binding。
 * @param {string} sessionID
 * @param {string} beforeEntryID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.MessagePageDTO>}
 */
export function MessagePage(sessionID, beforeEntryID, limit) {
    return $Call.ByID(2540075902, sessionID, beforeEntryID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * MessageWindow locates a search hit through the transcript location index and
 * reads only its nearby active-branch entries.
 * @param {string} sessionID
 * @param {string} entryID
 * @returns {$CancellablePromise<$models.MessagePageDTO>}
 */
export function MessageWindow(sessionID, entryID) {
    return $Call.ByID(4060073429, sessionID, entryID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Messages 返回 Session 当前 Active Branch 的最近消息。
 * 
 * SessionManager 返回的 Runtime Message 已经是 Eino *schema.Message。这里仅投影成旧
 * Vue DTO，不再从 JSONL metadata 猜测 ToolCall/Thinking。
 * @param {string} sessionID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.MessageDTO[]>}
 */
export function Messages(sessionID, limit) {
    return $Call.ByID(3505348282, sessionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ReadAttachment 按需读取 Session sidecar。前端只在图片进入历史视图时调用。
 * @param {string} sessionID
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentContentDTO>}
 */
export function ReadAttachment(sessionID, attachmentID) {
    return $Call.ByID(2267594691, sessionID, attachmentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Rename 修改 Session 名称。
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<$models.SessionDTO>}
 */
export function Rename(id, title) {
    return $Call.ByID(2444299400, id, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Search 先读可丢弃的 SQLite 投影；过期检查在后台执行。前端按 updating 轮询，
 * 因此首轮建索引不会把一次搜索请求挂起到两分钟。
 * @param {string} query
 * @returns {$CancellablePromise<$models.SessionSearchDTO>}
 */
export function Search(query) {
    return $Call.ByID(1649770302, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} id
 * @param {boolean} archived
 * @returns {$CancellablePromise<$models.SessionDTO>}
 */
export function SetArchived(id, archived) {
    return $Call.ByID(2826434976, id, archived).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SessionDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MessagePageDTO.createFrom;
const $$createType3 = $models.MessageDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.AttachmentContentDTO.createFrom;
const $$createType6 = $models.SessionSearchDTO.createFrom;
