// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SessionService 是 Session Domain 的 Wails Adapter。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Create 创建新 Session。
 * @param {string} projectID
 * @param {string} title
 * @returns {$CancellablePromise<$models.SessionDTO>}
 */
export function Create(projectID, title) {
    return $Call.ByID(1058013738, projectID, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete 删除 Session 与完整消息历史。
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Delete(id) {
    return $Call.ByID(373526041, id);
}

/**
 * List 返回 Project 的 Sessions。
 * @param {string} projectID
 * @returns {$CancellablePromise<$models.SessionDTO[]>}
 */
export function List(projectID) {
    return $Call.ByID(3883780506, projectID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Messages 返回 Session 当前 Active Branch 的最近消息。
 * 
 * SessionManager 返回的 Runtime Message 已经是 Eino *schema.Message。这里仅投影成旧
 * Vue DTO，不再从 JSONL metadata 猜测 ToolCall/Thinking。
 * @param {string} sessionID
 * @param {number} limit
 * @returns {$CancellablePromise<$models.MessageDTO[]>}
 */
export function Messages(sessionID, limit) {
    return $Call.ByID(3505348282, sessionID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ReadAttachment 按需读取 Session sidecar。前端只在图片进入历史视图时调用。
 * @param {string} sessionID
 * @param {string} attachmentID
 * @returns {$CancellablePromise<$models.AttachmentContentDTO>}
 */
export function ReadAttachment(sessionID, attachmentID) {
    return $Call.ByID(2267594691, sessionID, attachmentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Rename 修改 Session 名称。
 * @param {string} id
 * @param {string} title
 * @returns {$CancellablePromise<$models.SessionDTO>}
 */
export function Rename(id, title) {
    return $Call.ByID(2444299400, id, title).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SessionDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $models.MessageDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.AttachmentContentDTO.createFrom;
