// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SkillService 是本地 Skill Package 的 Wails Desktop Adapter。
 * 
 * 路径选择器属于桌面适配层；真正的目录安全校验、复制、哈希和 Runtime Snapshot 都由
 * skills.Manager 完成。文件详情也只通过 Manager 的受控只读接口按需读取。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckSkillUpdate 从记录的来源重新读取候选 Package，但不修改当前安装。
 * @param {string} name
 * @returns {$CancellablePromise<$models.SkillUpdateCheckDTO>}
 */
export function CheckSkillUpdate(name) {
    return $Call.ByID(1958035763, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteSkill 删除一个未被任何 Agent 引用的 Skill。
 * 
 * 不自动修改 Agent Profile 是刻意设计：删除 Skill 与修改 Agent 能力是两个控制面操作。
 * 如果仍被引用，用户必须先在“技能”工作区切换对应 Agent 并关闭 Skill，避免后台静默改变 Agent 行为。
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSkill(name) {
    return $Call.ByID(537268033, name);
}

/**
 * DisableSkillForAgent 从指定 Agent Profile 移除 Skill 引用。
 * 
 * Disable 允许清理已经 missing/invalid 的 stale 引用；当前 Turn 的冻结 Snapshot 不受影响。
 * @param {string} skillName
 * @param {string} agentID
 * @returns {$CancellablePromise<void>}
 */
export function DisableSkillForAgent(skillName, agentID) {
    return $Call.ByID(3584643746, skillName, agentID);
}

/**
 * DiscoverLocalSkillSource 扫描用户选择的本地 Skill/仓库目录，不执行安装。
 * @param {string} sourceDirectory
 * @returns {$CancellablePromise<$models.SkillDiscoveryDTO>}
 */
export function DiscoverLocalSkillSource(sourceDirectory) {
    return $Call.ByID(3553626393, sourceDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DiscoverSkillSource 扫描公开 HTTPS 仓库/归档中的 Skill，不修改本地 Catalog。
 * @param {string} sourceURL
 * @param {string} skillPath
 * @returns {$CancellablePromise<$models.SkillDiscoveryDTO>}
 */
export function DiscoverSkillSource(sourceURL, skillPath) {
    return $Call.ByID(4126813100, sourceURL, skillPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * EnableSkillForAgent 让指定 Agent 从下一 Turn 开始启用 Skill。
 * 
 * 关系的唯一事实来源仍然是 Agent.config.json 的 enabled_skills；SkillService 只提供从
 * Settings → Skills 方向操作同一份数据的 Desktop Adapter。
 * @param {string} skillName
 * @param {string} agentID
 * @returns {$CancellablePromise<void>}
 */
export function EnableSkillForAgent(skillName, agentID) {
    return $Call.ByID(3701639633, skillName, agentID);
}

/**
 * InstallDiscoveredSkillsFromDirectory 从本地仓库选择中原子安装多个 Skill。
 * @param {string} sourceDirectory
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.SkillDTO[]>}
 */
export function InstallDiscoveredSkillsFromDirectory(sourceDirectory, paths) {
    return $Call.ByID(132314325, sourceDirectory, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InstallDiscoveredSkillsFromURL 从同一次远程 Source 选择中原子安装多个 Skill。
 * @param {string} sourceURL
 * @param {string[]} paths
 * @returns {$CancellablePromise<$models.SkillDTO[]>}
 */
export function InstallDiscoveredSkillsFromURL(sourceURL, paths) {
    return $Call.ByID(2742911935, sourceURL, paths).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * InstallSkill 从用户明确选择的本地目录安装 Skill。
 * @param {string} sourceDirectory
 * @returns {$CancellablePromise<$models.SkillDTO>}
 */
export function InstallSkill(sourceDirectory) {
    return $Call.ByID(2833923151, sourceDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * InstallSkillFromURL 从公开 HTTPS Skill 来源安装 Skill。
 * 
 * 该 Desktop API 与 Agent 的 install_skill Tool 复用同一个 skills.Manager 远程安装实现，因此
 * 设置页不会拥有另一套网络/ZIP 安全规则。来源先经过可插拔 Resolver Registry；默认支持
 * Direct ZIP、GitHub、GitLab.com、Gitee 与 skills.sh。skillPath 只在一个仓库/归档中存在
 * 多个 SKILL.md 时需要；普通单 Skill ZIP 可以留空。
 * @param {string} sourceURL
 * @param {string} skillPath
 * @returns {$CancellablePromise<$models.SkillDTO>}
 */
export function InstallSkillFromURL(sourceURL, skillPath) {
    return $Call.ByID(1723334900, sourceURL, skillPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ReadSkillFile 为 Skill 详情页按需读取一个包内 UTF-8 文本文件。
 * 
 * 相对路径、symlink、哈希、大小和二进制检查都在 skills.Manager 内完成。scripts/ 文件在这里
 * 也只是文本预览，绝不会因为用户点击而执行。
 * @param {string} name
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.SkillFileContentDTO>}
 */
export function ReadSkillFile(name, relativePath) {
    return $Call.ByID(2938766646, name, relativePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ReinstallSkill 从已记录来源强制重新安装 Skill。
 * @param {string} name
 * @returns {$CancellablePromise<$models.SkillUpdateResultDTO>}
 */
export function ReinstallSkill(name) {
    return $Call.ByID(1717939582, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ReinstallSkillFromDirectory 为旧版本/手工安装的 Skill 建立本地来源，或显式更换来源。
 * @param {string} name
 * @param {string} sourceDirectory
 * @returns {$CancellablePromise<$models.SkillUpdateResultDTO>}
 */
export function ReinstallSkillFromDirectory(name, sourceDirectory) {
    return $Call.ByID(2214940089, name, sourceDirectory).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ReinstallSkillFromURL 为旧版本/手工安装的 Skill 建立远程来源，或显式更换来源。
 * @param {string} name
 * @param {string} sourceURL
 * @param {string} skillPath
 * @returns {$CancellablePromise<$models.SkillUpdateResultDTO>}
 */
export function ReinstallSkillFromURL(name, sourceURL, skillPath) {
    return $Call.ByID(1813950467, name, sourceURL, skillPath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SelectSkillDirectory 打开原生目录选择器，选择一个包含 SKILL.md 的本地目录。
 * 
 * 返回值仍被视为不可信输入，InstallSkill 会重新执行绝对路径、symlink、大小与包结构校验。
 * 用户取消时返回空字符串。
 * @param {string} currentPath
 * @returns {$CancellablePromise<string>}
 */
export function SelectSkillDirectory(currentPath) {
    return $Call.ByID(1721420383, currentPath);
}

/**
 * SetSkillAlias 设置或清除一个 Skill 的本地展示别名。
 * 
 * Alias 不写入第三方 SKILL.md，也不会进入 Agent enabled_skills 或 Runtime Snapshot。
 * @param {string} name
 * @param {string} alias
 * @returns {$CancellablePromise<void>}
 */
export function SetSkillAlias(name, alias) {
    return $Call.ByID(4238450306, name, alias);
}

/**
 * SkillDetail 按需返回一个有效 Skill 的文件树与稳定元数据。
 * 
 * 该方法不会返回任何文件正文；这样普通 Catalog 浏览不会把完整 Skill Package 常驻 WebView。
 * @param {string} name
 * @returns {$CancellablePromise<$models.SkillDetailDTO>}
 */
export function SkillDetail(name) {
    return $Call.ByID(844105653, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * State 返回当前已安装 Skill 与受控安装目录。
 * @returns {$CancellablePromise<$models.SkillStateDTO>}
 */
export function State() {
    return $Call.ByID(1261395296).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * UpdateSkill 从已记录来源更新 Skill；内容没有变化时不会做无意义的目录替换。
 * @param {string} name
 * @returns {$CancellablePromise<$models.SkillUpdateResultDTO>}
 */
export function UpdateSkill(name) {
    return $Call.ByID(2506265319, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.SkillUpdateCheckDTO.createFrom;
const $$createType1 = $models.SkillDiscoveryDTO.createFrom;
const $$createType2 = $models.SkillDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.SkillFileContentDTO.createFrom;
const $$createType5 = $models.SkillUpdateResultDTO.createFrom;
const $$createType6 = $models.SkillDetailDTO.createFrom;
const $$createType7 = $models.SkillStateDTO.createFrom;
