// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Archive(id) {
    return $Call.ByID(847694317, id);
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TaskRunDTO>}
 */
export function CancelRun(id) {
    return $Call.ByID(1641754548, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<string[]>}
 */
export function ClearRuns(taskID) {
    return $Call.ByID(1207175448, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {$models.SaveTaskRequest} request
 * @returns {$CancellablePromise<$models.TaskDTO>}
 */
export function Create(request) {
    return $Call.ByID(4028059765, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string[]>}
 */
export function Delete(id) {
    return $Call.ByID(4257845618, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<string[]>}
 */
export function DeleteRun(id) {
    return $Call.ByID(2626521267, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.TaskDTO[]>}
 */
export function List() {
    return $Call.ByID(2240024313).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} id
 * @returns {$CancellablePromise<$models.TaskRunDTO>}
 */
export function RunNow(id) {
    return $Call.ByID(1773366290, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} taskID
 * @returns {$CancellablePromise<$models.TaskRunDTO[]>}
 */
export function Runs(taskID) {
    return $Call.ByID(2479933411, taskID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SetStatus 立即暂停或恢复任务计划，不会覆盖其它尚未保存的编辑字段。
 * @param {string} id
 * @param {$models.TaskStatusRequest} request
 * @returns {$CancellablePromise<$models.TaskDTO>}
 */
export function SetStatus(id, request) {
    return $Call.ByID(3010972957, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @param {string} id
 * @param {$models.SaveTaskRequest} request
 * @returns {$CancellablePromise<$models.TaskDTO>}
 */
export function Update(id, request) {
    return $Call.ByID(1275451532, id, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TaskRunDTO.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.TaskDTO.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $Create.Array($$createType0);
