// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WorkspaceService 是 Wails Desktop 的工作区只读适配器。
 * 
 * 工作区页面只负责浏览当前文件系统。文件生成/修改/删除结果直接从对应聊天 Turn 的
 * Tool Trace 展示，不再通过这个服务扫描 Session 历史。
 * 
 * 所有查询都要求 AgentID，并由 Core 的 WorkspaceView Service 重新解析该 Agent 当前
 * Workspace；前端不能提交绝对 Workspace Root 来读取任意目录。
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as searchindex$0 from "../searchindex/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ListDirectory 懒加载工作区中的一个目录。
 * @param {string} agentID
 * @param {string} path
 * @returns {$CancellablePromise<$models.WorkspaceDirectoryDTO>}
 */
export function ListDirectory(agentID, path) {
    return $Call.ByID(449310502, agentID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Overview 返回指定 Agent Workspace 的总览。
 * @param {string} agentID
 * @returns {$CancellablePromise<$models.WorkspaceOverviewDTO>}
 */
export function Overview(agentID) {
    return $Call.ByID(1144069632, agentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * PreviewFile 返回安全受限的文件预览。
 * @param {string} agentID
 * @param {string} path
 * @returns {$CancellablePromise<$models.WorkspacePreviewDTO>}
 */
export function PreviewFile(agentID, path) {
    return $Call.ByID(3614391127, agentID, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SearchDocuments refreshes a bounded, disposable SQLite index of extractable
 * workspace documents. The Agent workspace is resolved anew on every call.
 * @param {string} agentID
 * @param {string} query
 * @returns {$CancellablePromise<searchindex$0.DocumentResult[]>}
 */
export function SearchDocuments(agentID, query) {
    return $Call.ByID(876288899, agentID, query).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.WorkspaceDirectoryDTO.createFrom;
const $$createType1 = $models.WorkspaceOverviewDTO.createFrom;
const $$createType2 = $models.WorkspacePreviewDTO.createFrom;
const $$createType3 = searchindex$0.DocumentResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
