package postgres

import (
	"context"
	"crypto/sha256"
	"errors"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

const SchemaVersion = 2

type migration struct {
	version    int
	name       string
	statements []string
}

// initialSchema 拼接初始表结构与索引语句，用于第一版迁移。
func initialSchema() []string {
	var out []string
	for _, sql := range schemaStatements {
		// 数据库扩展由迁移入口显式安装。
		if strings.Contains(sql, "CREATE EXTENSION") {
			continue
		}
		out = append(out, sql)
		switch {
		case strings.Contains(sql, "CREATE TABLE IF NOT EXISTS documents"):
			out = append(out, `ALTER TABLE documents ADD COLUMN IF NOT EXISTS markdown TEXT`)
		case strings.Contains(sql, "CREATE TABLE IF NOT EXISTS chunks"):
			out = append(out, `ALTER TABLE chunks ADD COLUMN IF NOT EXISTS chunk_type TEXT NOT NULL DEFAULT 'text'`,
				`ALTER TABLE chunks ADD COLUMN IF NOT EXISTS context_header TEXT NOT NULL DEFAULT ''`,
				`ALTER TABLE chunks ADD COLUMN IF NOT EXISTS parent_chunk_id TEXT`)
		case strings.Contains(sql, "CREATE TABLE IF NOT EXISTS retrieval_index"):
			out = append(out, `ALTER TABLE retrieval_index ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY`,
				`CREATE UNIQUE INDEX IF NOT EXISTS retrieval_index_id_key ON retrieval_index(id)`)
		}
	}
	return out
}

var lifecycleStatements = []string{
	`ALTER TABLE documents ADD COLUMN IF NOT EXISTS revision BIGINT NOT NULL DEFAULT 0`,
	`ALTER TABLE documents ADD COLUMN IF NOT EXISTS content_hash TEXT NOT NULL DEFAULT ''`,
	`ALTER TABLE documents ADD COLUMN IF NOT EXISTS process_config JSONB NOT NULL DEFAULT '{}'::jsonb`,
	`CREATE TABLE rag_collection_profiles (
 collection_id TEXT PRIMARY KEY, profile_id TEXT NOT NULL, descriptor JSONB NOT NULL,
 created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
)`,
	`CREATE TABLE rag_document_heads (
 collection_id TEXT NOT NULL, document_id TEXT NOT NULL, attempt BIGINT NOT NULL CHECK(attempt>0),
 deleted BOOLEAN NOT NULL DEFAULT false, PRIMARY KEY(collection_id,document_id)
)`,
	`ALTER TABLE chunks DROP CONSTRAINT IF EXISTS chunks_collection_id_parent_chunk_id_fkey`,
	`ALTER TABLE chunks ADD CONSTRAINT chunks_parent_fk FOREIGN KEY(collection_id,parent_chunk_id)
 REFERENCES chunks(collection_id,id) ON DELETE SET NULL (parent_chunk_id)`,
}

// Migrate 在数据库咨询锁保护下，以一个事务执行带版本和校验和的迁移，保留已识别旧表中的数据。
func Migrate(ctx context.Context, pool *pgxpool.Pool) error {
	if pool == nil {
		return errors.New("rag migrate: nil pool")
	}
	if err := CheckExtensions(ctx, pool); err != nil {
		return err
	}
	tx, err := pool.Begin(ctx)
	if err != nil {
		return err
	}
	defer rollbackTransaction(ctx, tx)
	if _, err = tx.Exec(ctx, `SET LOCAL statement_timeout='5min'`); err != nil {
		return err
	}
	if _, err = tx.Exec(ctx, `SELECT pg_advisory_xact_lock(736842510204)`); err != nil {
		return err
	}
	if _, err = tx.Exec(ctx, `CREATE TABLE IF NOT EXISTS rag_schema_migrations(version INTEGER PRIMARY KEY,name TEXT NOT NULL,checksum TEXT NOT NULL,applied_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`); err != nil {
		return err
	}
	var current int
	if err = tx.QueryRow(ctx, `SELECT COALESCE(MAX(version),0) FROM rag_schema_migrations`).Scan(&current); err != nil {
		return err
	}
	if current > SchemaVersion {
		return fmt.Errorf("rag migrate: database version %d is newer than supported %d", current, SchemaVersion)
	}
	for _, m := range []migration{{1, "initial and legacy adoption", initialSchema()}, {2, "profiles and document attempts", lifecycleStatements}} {
		checksum := fmt.Sprintf("%x", sha256.Sum256([]byte(strings.Join(m.statements, "\x00"))))
		var previous string
		err = tx.QueryRow(ctx, `SELECT checksum FROM rag_schema_migrations WHERE version=$1`, m.version).Scan(&previous)
		if err == nil {
			if previous != checksum {
				return fmt.Errorf("rag migrate: migration %d checksum mismatch", m.version)
			}
			continue
		}
		if !errors.Is(err, pgx.ErrNoRows) {
			return err
		}
		for i, sql := range m.statements {
			if _, err = tx.Exec(ctx, sql); err != nil {
				return fmt.Errorf("rag migration %d statement %d: %w", m.version, i+1, err)
			}
		}
		if _, err = tx.Exec(ctx, `INSERT INTO rag_schema_migrations(version,name,checksum)VALUES($1,$2,$3)`, m.version, m.name, checksum); err != nil {
			return err
		}
	}
	return tx.Commit(ctx)
}
