package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

// EmbeddingDimensions 是当前 Dense Embedding 固定维度。
//
// 当前第一版使用：
//
//	BGE-M3
//	1024 dimensions
//
// 后面如果需要支持多 embedding dimension，
// 不建议直接把这个值改成动态列；更适合做：
//
//	collection -> embedding profile
//
// 或独立 retrieval partition。
const EmbeddingDimensions = 1024

// schemaStatements 定义当前 RAG PostgreSQL Schema。
//
// documents:
//
//	文档级身份、完整 Markdown、metadata。
//
// chunks:
//
//	Parent + Child / 普通 Chunk。
//
// retrieval_index:
//
//	只保存真正参与检索的 Chunk。
//
// Parent Chunk:
//
//	存 chunks
//	不进入 retrieval_index
//
// Child Chunk:
//
//	存 chunks
//	进入 retrieval_index
var schemaStatements = []string{
	`
CREATE EXTENSION IF NOT EXISTS vector
`,

	`
CREATE EXTENSION IF NOT EXISTS pg_search
`,

	`
CREATE TABLE IF NOT EXISTS documents (
    collection_id TEXT NOT NULL,
    id            TEXT NOT NULL,
    title         TEXT NOT NULL DEFAULT '',
    markdown      TEXT,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, id)
)
`,

	`
CREATE TABLE IF NOT EXISTS chunks (
    collection_id   TEXT NOT NULL,
    id              TEXT NOT NULL,
    document_id     TEXT NOT NULL,

    -- text:
    --     普通可检索 Chunk / Parent-Child 中的 Child
    --
    -- parent_text:
    --     Parent Context，只保存、不直接检索
    chunk_type      TEXT NOT NULL DEFAULT 'text',

    chunk_index     INTEGER NOT NULL,

    content         TEXT NOT NULL,
    context_header  TEXT NOT NULL DEFAULT '',

    start_rune      INTEGER NOT NULL,
    end_rune        INTEGER NOT NULL,

    parent_chunk_id TEXT,

    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, id),

    FOREIGN KEY (collection_id, document_id)
        REFERENCES documents (collection_id, id)
        ON DELETE CASCADE,

    FOREIGN KEY (collection_id, parent_chunk_id)
        REFERENCES chunks (collection_id, id)
        ON DELETE SET NULL (parent_chunk_id),

    CHECK (chunk_index >= 0),
    CHECK (start_rune >= 0),
    CHECK (end_rune >= start_rune)
)
`,

	// -------------------------------------------------------------------------
	// 兼容我们前几个阶段已经创建过的开发数据库。
	//
	// 旧约束：
	//
	//     UNIQUE(collection_id, document_id, chunk_index)
	//
	// 在 Parent-Child 中会冲突：
	//
	//     parent index = 0
	//     child  index = 0
	//
	// 所以删除旧约束。
	// -------------------------------------------------------------------------
	`
ALTER TABLE chunks
DROP CONSTRAINT IF EXISTS chunks_collection_id_document_id_chunk_index_key
`,

	// Parent / Child 各自拥有独立的 Seq 空间。
	`
CREATE UNIQUE INDEX IF NOT EXISTS chunks_document_type_index_uq
ON chunks (
    collection_id,
    document_id,
    chunk_type,
    chunk_index
)
`,

	`
CREATE TABLE IF NOT EXISTS retrieval_index (
    -- ParadeDB 的独立 unique key_field。
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,

    collection_id TEXT NOT NULL,
    chunk_id       TEXT NOT NULL,
    document_id    TEXT NOT NULL,

    search_content TEXT NOT NULL,

    embedding      HALFVEC(1024) NOT NULL,

    enabled        BOOLEAN NOT NULL DEFAULT TRUE,

    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, chunk_id),

    FOREIGN KEY (collection_id, chunk_id)
        REFERENCES chunks (collection_id, id)
        ON DELETE CASCADE,

    FOREIGN KEY (collection_id, document_id)
        REFERENCES documents (collection_id, id)
        ON DELETE CASCADE
)
`,

	`
CREATE INDEX IF NOT EXISTS chunks_document_index_idx
ON chunks (
    collection_id,
    document_id,
    chunk_type,
    chunk_index
)
`,

	`
CREATE INDEX IF NOT EXISTS chunks_parent_idx
ON chunks (
    collection_id,
    parent_chunk_id
)
WHERE parent_chunk_id IS NOT NULL
`,

	`
CREATE INDEX IF NOT EXISTS retrieval_index_document_idx
ON retrieval_index (
    collection_id,
    document_id
)
`,

	`
CREATE INDEX IF NOT EXISTS retrieval_index_enabled_idx
ON retrieval_index (
    collection_id,
    enabled
)
`,

	// -------------------------------------------------------------------------
	// Dense Retrieval
	// -------------------------------------------------------------------------
	`
CREATE INDEX IF NOT EXISTS retrieval_index_embedding_hnsw_idx
ON retrieval_index
USING hnsw (
    embedding halfvec_cosine_ops
)
WITH (
    m = 16,
    ef_construction = 64
)
`,

	// -------------------------------------------------------------------------
	// ParadeDB BM25
	// -------------------------------------------------------------------------
	`
CREATE INDEX IF NOT EXISTS retrieval_index_search_idx
ON retrieval_index
USING paradedb (
    id,
    search_content,
    collection_id,
    enabled,
    chunk_id,
    document_id
)
WITH (
    key_field = 'id'
)
`,
}

// EnsureSchema is the development convenience alias for versioned migrations.
func EnsureSchema(ctx context.Context, pool *pgxpool.Pool) error { return Migrate(ctx, pool) }
