package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgxpool"
)

// EmbeddingDimensions 是当前 halfvec 列的固定维度，必须与知识库绑定的模型档案一致。
const EmbeddingDimensions = 1024

// 文档表保存完整原文，分块表保存父子关系，检索表仅保存可召回子块。
var schemaStatements = []string{
	`
CREATE EXTENSION IF NOT EXISTS vector
`,

	`
CREATE EXTENSION IF NOT EXISTS pg_search
`,

	`
CREATE TABLE IF NOT EXISTS documents (
    collection_id TEXT NOT NULL,
    id            TEXT NOT NULL,
    title         TEXT NOT NULL DEFAULT '',
    markdown      TEXT,
    metadata      JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, id)
)
`,

	`
CREATE TABLE IF NOT EXISTS chunks (
    collection_id   TEXT NOT NULL,
    id              TEXT NOT NULL,
    document_id     TEXT NOT NULL,

    -- text:
    --     普通可检索 Chunk / Parent-Child 中的 Child
    --
    -- parent_text:
    --     Parent Context，只保存、不直接检索
    chunk_type      TEXT NOT NULL DEFAULT 'text',

    chunk_index     INTEGER NOT NULL,

    content         TEXT NOT NULL,
    context_header  TEXT NOT NULL DEFAULT '',

    start_rune      INTEGER NOT NULL,
    end_rune        INTEGER NOT NULL,

    parent_chunk_id TEXT,

    metadata        JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, id),

    FOREIGN KEY (collection_id, document_id)
        REFERENCES documents (collection_id, id)
        ON DELETE CASCADE,

    FOREIGN KEY (collection_id, parent_chunk_id)
        REFERENCES chunks (collection_id, id)
        ON DELETE SET NULL (parent_chunk_id),

    CHECK (chunk_index >= 0),
    CHECK (start_rune >= 0),
    CHECK (end_rune >= start_rune)
)
`,

	// 旧分块序号约束未区分父子类型，需要在迁移中调整以允许各自从零编号。
	`
ALTER TABLE chunks
DROP CONSTRAINT IF EXISTS chunks_collection_id_document_id_chunk_index_key
`,

	// Parent / Child 各自拥有独立的 Seq 空间。
	`
CREATE UNIQUE INDEX IF NOT EXISTS chunks_document_type_index_uq
ON chunks (
    collection_id,
    document_id,
    chunk_type,
    chunk_index
)
`,

	`
CREATE TABLE IF NOT EXISTS retrieval_index (
    -- ParadeDB 的独立 unique key_field。
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE,

    collection_id TEXT NOT NULL,
    chunk_id       TEXT NOT NULL,
    document_id    TEXT NOT NULL,

    search_content TEXT NOT NULL,

    embedding      HALFVEC(1024) NOT NULL,

    enabled        BOOLEAN NOT NULL DEFAULT TRUE,

    metadata       JSONB NOT NULL DEFAULT '{}'::jsonb,

    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (collection_id, chunk_id),

    FOREIGN KEY (collection_id, chunk_id)
        REFERENCES chunks (collection_id, id)
        ON DELETE CASCADE,

    FOREIGN KEY (collection_id, document_id)
        REFERENCES documents (collection_id, id)
        ON DELETE CASCADE
)
`,

	`
CREATE INDEX IF NOT EXISTS chunks_document_index_idx
ON chunks (
    collection_id,
    document_id,
    chunk_type,
    chunk_index
)
`,

	`
CREATE INDEX IF NOT EXISTS chunks_parent_idx
ON chunks (
    collection_id,
    parent_chunk_id
)
WHERE parent_chunk_id IS NOT NULL
`,

	`
CREATE INDEX IF NOT EXISTS retrieval_index_document_idx
ON retrieval_index (
    collection_id,
    document_id
)
`,

	`
CREATE INDEX IF NOT EXISTS retrieval_index_enabled_idx
ON retrieval_index (
    collection_id,
    enabled
)
`,

	// 向量检索索引。
	`
CREATE INDEX IF NOT EXISTS retrieval_index_embedding_hnsw_idx
ON retrieval_index
USING hnsw (
    embedding halfvec_cosine_ops
)
WITH (
    m = 16,
    ef_construction = 64
)
`,

	// ParadeDB 关键词检索索引。
	`
CREATE INDEX IF NOT EXISTS retrieval_index_search_idx
ON retrieval_index
USING paradedb (
    id,
    search_content,
    collection_id,
    enabled,
    chunk_id,
    document_id
)
WITH (
    key_field = 'id'
)
`,
}

// EnsureSchema 为开发环境执行版本化迁移。
func EnsureSchema(ctx context.Context, pool *pgxpool.Pool) error { return Migrate(ctx, pool) }
