// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * RefreshResult 描述一次 Session Memory 刷新结果。
 * 
 * Updated=false 表示尚未达到自动刷新阈值且没有 force；这不是错误。Rebuilt=true 表示旧
 * Cursor 已不属于当前 ActiveBranch（例如 Retry/Fork），本次没有增量合并旧摘要，而是基于
 * 当前分支重新生成。
 */
export class RefreshResult {
    /**
     * Creates a new RefreshResult instance.
     * @param {Partial<RefreshResult>} [$$source = {}] - The source object to create the RefreshResult.
     */
    constructor($$source = {}) {
        if (!("updated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["updated"] = false;
        }
        if (!("rebuilt" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["rebuilt"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["coveredLeafId"] = undefined;
        }
        if (!("pendingUserTurns" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingUserTurns"] = 0;
        }
        if (!("pendingTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pendingTokens"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RefreshResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RefreshResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RefreshResult(/** @type {Partial<RefreshResult>} */($$parsedSource));
    }
}
