// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Assembly 描述下一次模型调用实际装配出来的 Context 结构，但不暴露 Prompt、Memory、
 * Message 正文或 Tool Arguments。它用于 Runtime/UI 检查“Context 由什么组成”，并与 Usage
 * 来自同一次 Engine.Build 投影，避免前端依据 Transcript 重新猜测。
 */
export class Assembly {
    /**
     * Creates a new Assembly instance.
     * @param {Partial<Assembly>} [$$source = {}] - The source object to create the Assembly.
     */
    constructor($$source = {}) {
        if (!("visibleMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["visibleMessageCount"] = 0;
        }
        if (!("recentMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recentMessageCount"] = 0;
        }
        if (!("userMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["userMessageCount"] = 0;
        }
        if (!("assistantMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assistantMessageCount"] = 0;
        }
        if (!("toolResultCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolResultCount"] = 0;
        }
        if (!("toolCallCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolCallCount"] = 0;
        }
        if (!("memoryInjected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["memoryInjected"] = false;
        }
        if (!("checkpointInjected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checkpointInjected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestCompactionID"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assembly instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Assembly}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Assembly(/** @type {Partial<Assembly>} */($$parsedSource));
    }
}

/**
 * CompactResult 是压缩完成后的稳定结果。
 */
export class CompactResult {
    /**
     * Creates a new CompactResult instance.
     * @param {Partial<CompactResult>} [$$source = {}] - The source object to create the CompactResult.
     */
    constructor($$source = {}) {
        if (!("compacted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["compacted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["compactionID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["firstKeptEntryID"] = undefined;
        }
        if (!("before" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["before"] = (new Usage());
        }
        if (!("after" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["after"] = (new Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompactResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("before" in $$parsedSource) {
            $$parsedSource["before"] = $$createField3_0($$parsedSource["before"]);
        }
        if ("after" in $$parsedSource) {
            $$parsedSource["after"] = $$createField4_0($$parsedSource["after"]);
        }
        return new CompactResult(/** @type {Partial<CompactResult>} */($$parsedSource));
    }
}

/**
 * Usage 描述某个 Session 在当前模型下的上下文使用情况。
 * 
 * UsedTokens 是 Humbert 的本地估算值。Provider 最近一次真实 prompt usage 会继续保存在
 * AssistantMessage 中，但 UI/压缩规划不能只依赖它，因为最新 ToolResult、System Prompt
 * 和 Tool Schema 可能尚未包含在该 usage 中。
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("contextWindow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindow"] = 0;
        }
        if (!("usedTokens" in $$source)) {
            /**
             * UsedTokens 是下一次模型请求预计占用的总 Context Token。它必须始终等于下面
             * System/Tool/Memory/Checkpoint/Message 五类占用之和，前端据此展示环形进度。
             * @member
             * @type {number}
             */
            this["usedTokens"] = 0;
        }
        if (!("systemTokens" in $$source)) {
            /**
             * SystemTokens 是稳定 Agent/Runtime Instruction 的估算占用。新 Session 即使没有
             * Message，也会因为这部分以及 Tool Schema 存在基础 Context 开销。
             * @member
             * @type {number}
             */
            this["systemTokens"] = 0;
        }
        if (!("toolTokens" in $$source)) {
            /**
             * ToolTokens 是本 Turn 冻结 Tool Definitions/JSON Schema 的估算占用。这里不包含
             * ToolCall/ToolResult 历史；后者属于 MessageTokens。
             * @member
             * @type {number}
             */
            this["toolTokens"] = 0;
        }
        if (!("memoryTokens" in $$source)) {
            /**
             * MemoryTokens 是当前有效 Session Memory Key Facts 及其注入标题/分隔符的占用。
             * Timeline 不注入主模型，因此不会计入该字段。
             * @member
             * @type {number}
             */
            this["memoryTokens"] = 0;
        }
        if (!("checkpointTokens" in $$source)) {
            /**
             * CheckpointTokens 是最新持久化 Compaction Checkpoint 的模型可见占用。没有发生过
             * durable compaction 时为 0。旧 checkpoint 已被最新 checkpoint 递归吸收，不重复计。
             * @member
             * @type {number}
             */
            this["checkpointTokens"] = 0;
        }
        if (!("messageTokens" in $$source)) {
            /**
             * MessageTokens 是当前 firstKeptEntryId 之后 Recent ActiveBranch 原始消息的占用，
             * 包括 User/Assistant、按策略回放的 Thinking、ToolCall 与 ToolResult。
             * @member
             * @type {number}
             */
            this["messageTokens"] = 0;
        }
        if (!("reserveTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reserveTokens"] = 0;
        }
        if (!("thresholdTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["thresholdTokens"] = 0;
        }
        if (!("keepRecentTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["keepRecentTokens"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("needsCompaction" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsCompaction"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestCompactionID"] = undefined;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = Usage.createFrom;
