// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Assembly 描述下一次模型调用实际装配出来的 Context 结构，但不暴露 Prompt、Memory、
 * Message 正文或 Tool Arguments。它用于 Runtime/UI 检查“Context 由什么组成”，并与 Usage
 * 来自同一次 Engine.Build 投影，避免前端依据 Transcript 重新猜测。
 */
export class Assembly {
    /**
     * Creates a new Assembly instance.
     * @param {Partial<Assembly>} [$$source = {}] - The source object to create the Assembly.
     */
    constructor($$source = {}) {
        if (!("visibleMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["visibleMessageCount"] = 0;
        }
        if (!("recentMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["recentMessageCount"] = 0;
        }
        if (!("userMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["userMessageCount"] = 0;
        }
        if (!("assistantMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["assistantMessageCount"] = 0;
        }
        if (!("toolResultCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolResultCount"] = 0;
        }
        if (!("toolCallCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolCallCount"] = 0;
        }
        if (!("memoryInjected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["memoryInjected"] = false;
        }
        if (!("referenceMessageCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["referenceMessageCount"] = 0;
        }
        if (!("checkpointInjected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["checkpointInjected"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestCompactionID"] = undefined;
        }
        if (!("window" in $$source)) {
            /**
             * @member
             * @type {WindowState}
             */
            this["window"] = (new WindowState());
        }
        if (!("retainedStateAvailable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["retainedStateAvailable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Assembly instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Assembly}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("window" in $$parsedSource) {
            $$parsedSource["window"] = $$createField10_0($$parsedSource["window"]);
        }
        return new Assembly(/** @type {Partial<Assembly>} */($$parsedSource));
    }
}

/**
 * CompactResult 是压缩完成后的稳定结果。
 */
export class CompactResult {
    /**
     * Creates a new CompactResult instance.
     * @param {Partial<CompactResult>} [$$source = {}] - The source object to create the CompactResult.
     */
    constructor($$source = {}) {
        if (!("compacted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["compacted"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["compactionID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["firstKeptEntryID"] = undefined;
        }
        if (!("before" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["before"] = (new Usage());
        }
        if (!("after" in $$source)) {
            /**
             * @member
             * @type {Usage}
             */
            this["after"] = (new Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CompactResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CompactResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("before" in $$parsedSource) {
            $$parsedSource["before"] = $$createField3_0($$parsedSource["before"]);
        }
        if ("after" in $$parsedSource) {
            $$parsedSource["after"] = $$createField4_0($$parsedSource["after"]);
        }
        return new CompactResult(/** @type {Partial<CompactResult>} */($$parsedSource));
    }
}

/**
 * Usage 描述某个 Session 在当前模型下的上下文使用情况。
 * 
 * UsedTokens 是 Humbert 的本地估算值。Provider 最近一次真实 prompt usage 会继续保存在
 * AssistantMessage 中，但 UI/压缩规划不能只依赖它，因为最新 ToolResult、System Prompt
 * 和 Tool Schema 可能尚未包含在该 usage 中。
 */
export class Usage {
    /**
     * Creates a new Usage instance.
     * @param {Partial<Usage>} [$$source = {}] - The source object to create the Usage.
     */
    constructor($$source = {}) {
        if (!("contextWindow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindow"] = 0;
        }
        if (!("usedTokens" in $$source)) {
            /**
             * UsedTokens 是下一次模型请求预计占用的总 Context Token。它必须始终等于下面
             * System/Tool/Memory/Checkpoint/Message 五类占用之和，前端据此展示环形进度。
             * @member
             * @type {number}
             */
            this["usedTokens"] = 0;
        }
        if (!("systemTokens" in $$source)) {
            /**
             * SystemTokens 是稳定 Agent/Runtime Instruction 的估算占用。新 Session 即使没有
             * Message，也会因为这部分以及 Tool Schema 存在基础 Context 开销。
             * @member
             * @type {number}
             */
            this["systemTokens"] = 0;
        }
        if (!("toolTokens" in $$source)) {
            /**
             * ToolTokens 是本 Turn 冻结 Tool Definitions/JSON Schema 的估算占用。这里不包含
             * ToolCall/ToolResult 历史；后者属于 MessageTokens。
             * @member
             * @type {number}
             */
            this["toolTokens"] = 0;
        }
        if (!("memoryTokens" in $$source)) {
            /**
             * MemoryTokens 是当前有效 Session Memory Key Facts 及其注入标题/分隔符的占用。
             * Timeline 不注入主模型，因此不会计入该字段。
             * @member
             * @type {number}
             */
            this["memoryTokens"] = 0;
        }
        if (!("referenceTokens" in $$source)) {
            /**
             * ReferenceTokens 保留给未来低权限 Session Reference；当前同步子 Agent 结果已经作为
             * 标准 ToolResult 存在于父 Session，不需要额外注入。
             * @member
             * @type {number}
             */
            this["referenceTokens"] = 0;
        }
        if (!("checkpointTokens" in $$source)) {
            /**
             * CheckpointTokens 是最新持久化 Compaction Checkpoint 的模型可见占用。没有发生过
             * durable compaction 时为 0。旧 checkpoint 已被最新 checkpoint 递归吸收，不重复计。
             * @member
             * @type {number}
             */
            this["checkpointTokens"] = 0;
        }
        if (!("messageTokens" in $$source)) {
            /**
             * MessageTokens 是当前 firstKeptEntryId 之后 Recent ActiveBranch 原始消息的占用，
             * 包括 User/Assistant、按策略回放的 Thinking、ToolCall 与 ToolResult。
             * @member
             * @type {number}
             */
            this["messageTokens"] = 0;
        }
        if (!("reserveTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reserveTokens"] = 0;
        }
        if (!("thresholdTokens" in $$source)) {
            /**
             * ThresholdTokens 是模型输入的硬安全线。达到该值后，下一次模型调用前必须完成压缩。
             * @member
             * @type {number}
             */
            this["thresholdTokens"] = 0;
        }
        if (!("softThresholdTokens" in $$source)) {
            /**
             * SoftThresholdTokens 是主动维护线。Turn 已完成且达到该值时，可以提前换到新的工作窗口，
             * 避免下一次用户消息等待同步压缩。
             * @member
             * @type {number}
             */
            this["softThresholdTokens"] = 0;
        }
        if (!("keepRecentTokens" in $$source)) {
            /**
             * KeepRecentTokens 保留旧字段语义，等于当前轮次最终计算出的 TargetRecentTokens。
             * @member
             * @type {number}
             */
            this["keepRecentTokens"] = 0;
        }
        if (!("preferredRecentTokens" in $$source)) {
            /**
             * PreferredRecentTokens 是配置希望保留的最近原始历史；TargetRecentTokens 则会根据本轮
             * System/Tool/Memory 等固定占用动态收缩。
             * @member
             * @type {number}
             */
            this["preferredRecentTokens"] = 0;
        }
        if (!("targetRecentTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetRecentTokens"] = 0;
        }
        if (!("fixedTokens" in $$source)) {
            /**
             * FixedTokens 是不能通过压缩对话历史释放的占用。HistoryBudgetTokens 是硬阈值扣除
             * FixedTokens 后真正留给“检查点 + 最近原始消息”的容量。
             * @member
             * @type {number}
             */
            this["fixedTokens"] = 0;
        }
        if (!("historyBudgetTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["historyBudgetTokens"] = 0;
        }
        if (!("checkpointBudgetTokens" in $$source)) {
            /**
             * CheckpointBudgetTokens 是压缩器为交接检查点预留的建议预算。它不是强制输出长度，
             * 但会参与 TargetRecentTokens 计算，避免最近历史把检查点空间全部吃掉。
             * @member
             * @type {number}
             */
            this["checkpointBudgetTokens"] = 0;
        }
        if (!("percent" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("needsCompaction" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsCompaction"] = false;
        }
        if (!("needsSoftCompaction" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["needsSoftCompaction"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latestCompactionID"] = undefined;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Usage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Usage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Usage(/** @type {Partial<Usage>} */($$parsedSource));
    }
}

/**
 * WindowState 描述当前模型工作窗口。工作窗口不是另一份历史文件，而是完整会话记录上
 * 的一个逻辑阶段：每次 durable compaction 完成后 generation +1，并由最新检查点与
 * firstKeptEntryId 确定新窗口的起点。
 */
export class WindowState {
    /**
     * Creates a new WindowState instance.
     * @param {Partial<WindowState>} [$$source = {}] - The source object to create the WindowState.
     */
    constructor($$source = {}) {
        if (!("generation" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["generation"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["startEntryID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["checkpointID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceFirstEntryID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sourceLastEntryID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sourceEntryCount"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WindowState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowState(/** @type {Partial<WindowState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WindowState.createFrom;
const $$createType1 = Usage.createFrom;
