// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as approval$0 from "../approval/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as contextengine$0 from "../contextengine/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "../memory/models.js";

/**
 * ActiveRunStatus 是当前 Session 活动 Turn 的安全只读投影。
 */
export class ActiveRunStatus {
    /**
     * Creates a new ActiveRunStatus instance.
     * @param {Partial<ActiveRunStatus>} [$$source = {}] - The source object to create the ActiveRunStatus.
     */
    constructor($$source = {}) {
        if (!("requestID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestID"] = "";
        }
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {RunPhase}
             */
            this["phase"] = RunPhase.$zero;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["waitingApprovalID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Approval 仅在 waiting_approval 阶段提供 Permission 层已经脱敏的安全请求，便于 UI
             * 在重新挂载后恢复审批卡片；raw Tool Arguments 仍不会通过该状态接口暴露。
             * @member
             * @type {approval$0.Request | null | undefined}
             */
            this["approval"] = undefined;
        }
        if (!("runtime" in $$source)) {
            /**
             * Runtime 是活动 Turn 已经冻结的 Manifest。它可能与 ContextOverview.Runtime（下一 Turn）
             * 不同，因此 UI 能明确区分“正在执行什么”和“下一次会执行什么”。
             * @member
             * @type {RuntimeManifest}
             */
            this["runtime"] = (new RuntimeManifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ActiveRunStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ActiveRunStatus}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("approval" in $$parsedSource) {
            $$parsedSource["approval"] = $$createField6_0($$parsedSource["approval"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField7_0($$parsedSource["runtime"]);
        }
        return new ActiveRunStatus(/** @type {Partial<ActiveRunStatus>} */($$parsedSource));
    }
}

/**
 * ContextOverview 把 Context Usage、Context Assembly、下一 Turn Runtime Manifest 与当前活动
 * Turn 状态放在一个只读快照中。UI 因此不需要跨多个 Store 自行推导 Runtime 生命周期。
 */
export class ContextOverview {
    /**
     * Creates a new ContextOverview instance.
     * @param {Partial<ContextOverview>} [$$source = {}] - The source object to create the ContextOverview.
     */
    constructor($$source = {}) {
        if (!("usage" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.Usage}
             */
            this["usage"] = (new contextengine$0.Usage());
        }
        if (!("assembly" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.Assembly}
             */
            this["assembly"] = (new contextengine$0.Assembly());
        }
        if (!("runtime" in $$source)) {
            /**
             * @member
             * @type {RuntimeManifest}
             */
            this["runtime"] = (new RuntimeManifest());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ActiveRunStatus | null | undefined}
             */
            this["active"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ContextOverview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ContextOverview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("usage" in $$parsedSource) {
            $$parsedSource["usage"] = $$createField0_0($$parsedSource["usage"]);
        }
        if ("assembly" in $$parsedSource) {
            $$parsedSource["assembly"] = $$createField1_0($$parsedSource["assembly"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField2_0($$parsedSource["runtime"]);
        }
        if ("active" in $$parsedSource) {
            $$parsedSource["active"] = $$createField3_0($$parsedSource["active"]);
        }
        return new ContextOverview(/** @type {Partial<ContextOverview>} */($$parsedSource));
    }
}

/**
 * Event 是 Runtime -> Desktop Adapter 的统一实时协议。
 */
export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {EventType}
             */
            this["type"] = EventType.$zero;
        }
        if (!("requestID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestID"] = "";
        }
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("agentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentID"] = "";
        }
        if (!("modelID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelID"] = "";
        }
        if (!("modelRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelRevision"] = 0;
        }
        if (!("toolRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolRevision"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["builtinToolNames"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sandboxProfile"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sandboxNetworkMode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sandboxNativeBackend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillRevision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["skillNames"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mcpRevision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {mcp$0.RuntimeServerSnapshot[] | undefined}
             */
            this["mcpServers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {mcp$0.RuntimeToolSnapshot[] | undefined}
             */
            this["mcpTools"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["mcpToolNames"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Runtime 只在 turn.started 中提供，表示该 Turn 已经冻结的统一 Runtime Manifest。
             * 上面的扁平字段继续保留兼容现有前端/日志消费者。
             * @member
             * @type {RuntimeManifest | null | undefined}
             */
            this["runtime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["delta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["messageID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolCallID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolArguments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["durationMS"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Approval 只在 approval.* Runtime Event 中存在。Request 本身不包含 raw Tool
             * Arguments，只包含 Permission 层已经脱敏的 Presentation。
             * @member
             * @type {approval$0.Request | null | undefined}
             */
            this["approval"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ApprovalDecision 只在 approval.resolved 中存在，用于前端把卡片切换到终态。
             * @member
             * @type {approval$0.Decision | undefined}
             */
            this["approvalDecision"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["occurredAt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType7;
        const $$createField13_0 = $$createType7;
        const $$createField15_0 = $$createType9;
        const $$createField16_0 = $$createType11;
        const $$createField17_0 = $$createType7;
        const $$createField18_0 = $$createType12;
        const $$createField26_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("builtinToolNames" in $$parsedSource) {
            $$parsedSource["builtinToolNames"] = $$createField8_0($$parsedSource["builtinToolNames"]);
        }
        if ("skillNames" in $$parsedSource) {
            $$parsedSource["skillNames"] = $$createField13_0($$parsedSource["skillNames"]);
        }
        if ("mcpServers" in $$parsedSource) {
            $$parsedSource["mcpServers"] = $$createField15_0($$parsedSource["mcpServers"]);
        }
        if ("mcpTools" in $$parsedSource) {
            $$parsedSource["mcpTools"] = $$createField16_0($$parsedSource["mcpTools"]);
        }
        if ("mcpToolNames" in $$parsedSource) {
            $$parsedSource["mcpToolNames"] = $$createField17_0($$parsedSource["mcpToolNames"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField18_0($$parsedSource["runtime"]);
        }
        if ("approval" in $$parsedSource) {
            $$parsedSource["approval"] = $$createField26_0($$parsedSource["approval"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * EventType 是 Runtime -> Desktop 的瞬时事件类型。
 * 
 * 这些事件只用于流式 UI，不属于 Session 持久化协议。assistant.delta、reasoning.delta
 * 和 tool.* 都不会逐条写入 JSONL；只有完整 schema.Message 终态进入 SessionManager。
 * @readonly
 * @enum {string}
 */
export const EventType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EventTurnStarted: "turn.started",
    EventTurnMaintaining: "turn.maintaining",
    EventAssistantReasoningDelta: "assistant.reasoning.delta",
    EventAssistantDelta: "assistant.delta",
    EventToolStarted: "tool.started",
    EventToolCompleted: "tool.completed",
    EventToolFailed: "tool.failed",
    EventApprovalRequested: "approval.requested",
    EventApprovalResolved: "approval.resolved",
    EventApprovalExpired: "approval.expired",
    EventTurnCompleted: "turn.completed",
    EventTurnFailed: "turn.failed",
    EventTurnCancelled: "turn.cancelled",
};

/**
 * ManualCompactionResult 是用户主动执行“压缩”或“压缩并更新”的结果。
 * 
 * Memory 仅在 updateMemory=true 且刷新成功时 Updated=true；普通压缩不会隐式更新 Memory，
 * 与前端两个菜单动作保持清晰语义。
 */
export class ManualCompactionResult {
    /**
     * Creates a new ManualCompactionResult instance.
     * @param {Partial<ManualCompactionResult>} [$$source = {}] - The source object to create the ManualCompactionResult.
     */
    constructor($$source = {}) {
        if (!("compaction" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.CompactResult}
             */
            this["compaction"] = (new contextengine$0.CompactResult());
        }
        if (!("memory" in $$source)) {
            /**
             * @member
             * @type {memory$0.RefreshResult}
             */
            this["memory"] = (new memory$0.RefreshResult());
        }
        if (!("contextUsage" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.Usage}
             */
            this["contextUsage"] = (new contextengine$0.Usage());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ManualCompactionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ManualCompactionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType14;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("compaction" in $$parsedSource) {
            $$parsedSource["compaction"] = $$createField0_0($$parsedSource["compaction"]);
        }
        if ("memory" in $$parsedSource) {
            $$parsedSource["memory"] = $$createField1_0($$parsedSource["memory"]);
        }
        if ("contextUsage" in $$parsedSource) {
            $$parsedSource["contextUsage"] = $$createField2_0($$parsedSource["contextUsage"]);
        }
        return new ManualCompactionResult(/** @type {Partial<ManualCompactionResult>} */($$parsedSource));
    }
}

/**
 * ResolveApprovalResult 告诉前端审批已被 Runtime 接受。真正 Tool 执行和后续 Assistant
 * 继续通过原有 runtime events 异步返回。
 */
export class ResolveApprovalResult {
    /**
     * Creates a new ResolveApprovalResult instance.
     * @param {Partial<ResolveApprovalResult>} [$$source = {}] - The source object to create the ResolveApprovalResult.
     */
    constructor($$source = {}) {
        if (!("approval" in $$source)) {
            /**
             * @member
             * @type {approval$0.Request}
             */
            this["approval"] = (new approval$0.Request());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResolveApprovalResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ResolveApprovalResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("approval" in $$parsedSource) {
            $$parsedSource["approval"] = $$createField0_0($$parsedSource["approval"]);
        }
        return new ResolveApprovalResult(/** @type {Partial<ResolveApprovalResult>} */($$parsedSource));
    }
}

/**
 * RunPhase 是一个活动 User Turn 的进程内生命周期状态。
 * 
 * 它不是 Transcript 历史状态：Turn 进入 completed/failed/cancelled 后会从活动表移除，
 * 终态仍由 runtime event + Session JSONL 表达。该状态主要用于 UI 重连/重新挂载时恢复。
 * @readonly
 * @enum {string}
 */
export const RunPhase = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RunPhaseRunning: "running",
    RunPhaseMaintaining: "maintaining",
    RunPhaseWaitingApproval: "waiting_approval",
    RunPhaseCancelling: "cancelling",
};

/**
 * RuntimeManifest 是一次 Runtime Resolve 后对“这个 Agent 下一次请求会携带什么能力”的
 * 稳定只读描述。它不包含可执行 Model/Tool 实例，也不包含 Prompt 正文，因此可以安全地
 * 暴露给 Desktop UI 做 Context/Capability 检查。
 * 
 * Manifest 与真正的 Turn Snapshot 由同一个 Resolver 生成；Settings 修改只会影响下一次
 * Resolve，正在执行的 Turn 仍然使用已经冻结的 Snapshot。
 */
export class RuntimeManifest {
    /**
     * Creates a new RuntimeManifest instance.
     * @param {Partial<RuntimeManifest>} [$$source = {}] - The source object to create the RuntimeManifest.
     */
    constructor($$source = {}) {
        if (!("projectID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectID"] = "";
        }
        if (!("projectName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectName"] = "";
        }
        if (!("agentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentID"] = "";
        }
        if (!("agentName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentName"] = "";
        }
        if (!("modelID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelID"] = "";
        }
        if (!("modelDisplayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modelDisplayName"] = "";
        }
        if (!("modelRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelRevision"] = 0;
        }
        if (!("toolRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toolRevision"] = 0;
        }
        if (!("builtinToolNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["builtinToolNames"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skillRevision"] = undefined;
        }
        if (!("skillNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["skillNames"] = [];
        }
        if (!("mcpRevision" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["mcpRevision"] = 0;
        }
        if (!("mcpServers" in $$source)) {
            /**
             * @member
             * @type {mcp$0.RuntimeServerSnapshot[]}
             */
            this["mcpServers"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {mcp$0.RuntimeServerFailure[] | undefined}
             */
            this["mcpUnavailable"] = undefined;
        }
        if (!("mcpTools" in $$source)) {
            /**
             * @member
             * @type {mcp$0.RuntimeToolSnapshot[]}
             */
            this["mcpTools"] = [];
        }
        if (!("mcpToolNames" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["mcpToolNames"] = [];
        }
        if (!("exposedToolNames" in $$source)) {
            /**
             * ExposedToolNames 是模型侧最终可见 Tool 名称的稳定并集：Builtin + MCP + Skill。
             * 该字段只用于检查/展示，不代替真正的 []tool.BaseTool。
             * @member
             * @type {string[]}
             */
            this["exposedToolNames"] = [];
        }
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {RuntimeWorkspaceManifest}
             */
            this["workspace"] = (new RuntimeWorkspaceManifest());
        }
        if (!("sandbox" in $$source)) {
            /**
             * @member
             * @type {RuntimeSandboxManifest}
             */
            this["sandbox"] = (new RuntimeSandboxManifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeManifest}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType7;
        const $$createField10_0 = $$createType7;
        const $$createField12_0 = $$createType9;
        const $$createField13_0 = $$createType16;
        const $$createField14_0 = $$createType11;
        const $$createField15_0 = $$createType7;
        const $$createField16_0 = $$createType7;
        const $$createField17_0 = $$createType17;
        const $$createField18_0 = $$createType18;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("builtinToolNames" in $$parsedSource) {
            $$parsedSource["builtinToolNames"] = $$createField8_0($$parsedSource["builtinToolNames"]);
        }
        if ("skillNames" in $$parsedSource) {
            $$parsedSource["skillNames"] = $$createField10_0($$parsedSource["skillNames"]);
        }
        if ("mcpServers" in $$parsedSource) {
            $$parsedSource["mcpServers"] = $$createField12_0($$parsedSource["mcpServers"]);
        }
        if ("mcpUnavailable" in $$parsedSource) {
            $$parsedSource["mcpUnavailable"] = $$createField13_0($$parsedSource["mcpUnavailable"]);
        }
        if ("mcpTools" in $$parsedSource) {
            $$parsedSource["mcpTools"] = $$createField14_0($$parsedSource["mcpTools"]);
        }
        if ("mcpToolNames" in $$parsedSource) {
            $$parsedSource["mcpToolNames"] = $$createField15_0($$parsedSource["mcpToolNames"]);
        }
        if ("exposedToolNames" in $$parsedSource) {
            $$parsedSource["exposedToolNames"] = $$createField16_0($$parsedSource["exposedToolNames"]);
        }
        if ("workspace" in $$parsedSource) {
            $$parsedSource["workspace"] = $$createField17_0($$parsedSource["workspace"]);
        }
        if ("sandbox" in $$parsedSource) {
            $$parsedSource["sandbox"] = $$createField18_0($$parsedSource["sandbox"]);
        }
        return new RuntimeManifest(/** @type {Partial<RuntimeManifest>} */($$parsedSource));
    }
}

/**
 * RuntimeSandboxManifest 描述本 Turn 真正生效的 Sandbox，而不是 Agent Profile 中的原始覆盖值。
 */
export class RuntimeSandboxManifest {
    /**
     * Creates a new RuntimeSandboxManifest instance.
     * @param {Partial<RuntimeSandboxManifest>} [$$source = {}] - The source object to create the RuntimeSandboxManifest.
     */
    constructor($$source = {}) {
        if (!("profile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profile"] = "";
        }
        if (!("networkMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["networkMode"] = "";
        }
        if (!("nativeMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nativeMode"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["nativeBackend"] = undefined;
        }
        if (!("nativeReady" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nativeReady"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeSandboxManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeSandboxManifest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeSandboxManifest(/** @type {Partial<RuntimeSandboxManifest>} */($$parsedSource));
    }
}

/**
 * RuntimeWorkspaceManifest 是 Runtime Snapshot 中 Workspace 的安全只读投影。
 */
export class RuntimeWorkspaceManifest {
    /**
     * Creates a new RuntimeWorkspaceManifest instance.
     * @param {Partial<RuntimeWorkspaceManifest>} [$$source = {}] - The source object to create the RuntimeWorkspaceManifest.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mode"] = "";
        }
        if (!("rootDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootDir"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeWorkspaceManifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeWorkspaceManifest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeWorkspaceManifest(/** @type {Partial<RuntimeWorkspaceManifest>} */($$parsedSource));
    }
}

/**
 * StartTurnResult 是异步 Turn 启动结果。
 */
export class StartTurnResult {
    /**
     * Creates a new StartTurnResult instance.
     * @param {Partial<StartTurnResult>} [$$source = {}] - The source object to create the StartTurnResult.
     */
    constructor($$source = {}) {
        if (!("requestID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestID"] = "";
        }
        if (!("runID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runID"] = "";
        }
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("userMessageID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userMessageID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * StartError 表示用户消息已保存，但运行初始化失败；Desktop 仍须返回收据用于安全重试。
             * @member
             * @type {string | undefined}
             */
            this["startError"] = undefined;
        }
        if (!("contextUsage" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.Usage}
             */
            this["contextUsage"] = (new contextengine$0.Usage());
        }
        if (!("contextAssembly" in $$source)) {
            /**
             * @member
             * @type {contextengine$0.Assembly}
             */
            this["contextAssembly"] = (new contextengine$0.Assembly());
        }
        if (!("runtime" in $$source)) {
            /**
             * Runtime 是这个已经启动的 Turn 真正冻结的 Manifest；它可能与发送前最后一次
             * ContextOverview 不同（例如用户刚修改过 Agent 设置），因此由 StartTurnResult 回传。
             * @member
             * @type {RuntimeManifest}
             */
            this["runtime"] = (new RuntimeManifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StartTurnResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StartTurnResult}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType3;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contextUsage" in $$parsedSource) {
            $$parsedSource["contextUsage"] = $$createField5_0($$parsedSource["contextUsage"]);
        }
        if ("contextAssembly" in $$parsedSource) {
            $$parsedSource["contextAssembly"] = $$createField6_0($$parsedSource["contextAssembly"]);
        }
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField7_0($$parsedSource["runtime"]);
        }
        return new StartTurnResult(/** @type {Partial<StartTurnResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = approval$0.Request.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = RuntimeManifest.createFrom;
const $$createType3 = contextengine$0.Usage.createFrom;
const $$createType4 = contextengine$0.Assembly.createFrom;
const $$createType5 = ActiveRunStatus.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = mcp$0.RuntimeServerSnapshot.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = mcp$0.RuntimeToolSnapshot.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $Create.Nullable($$createType2);
const $$createType13 = contextengine$0.CompactResult.createFrom;
const $$createType14 = memory$0.RefreshResult.createFrom;
const $$createType15 = mcp$0.RuntimeServerFailure.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = RuntimeWorkspaceManifest.createFrom;
const $$createType18 = RuntimeSandboxManifest.createFrom;
