// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as notifications$0 from "../../../../sda1-hacker/humbert-agent/internal/notifications/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as proactive$0 from "../../../../sda1-hacker/humbert-agent/internal/proactive/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as runtime$0 from "../../../../sda1-hacker/humbert-agent/internal/runtime/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as tasks$0 from "../../../../sda1-hacker/humbert-agent/internal/tasks/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "humbert:notification": notifications$0.Notification;
            "humbert:proactive:event": proactive$0.PublicEvent;
            "humbert:runtime:event": runtime$0.Event;
            "humbert:task:event": tasks$0.Event;
        }
    }
}
