// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as runtime$0 from "../../../../sda1-hacker/humbert-agent/internal/runtime/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "humbert:runtime:event": runtime$0.Event;
        }
    }
}
