// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class DocumentResult {
    /**
     * Creates a new DocumentResult instance.
     * @param {Partial<DocumentResult>} [$$source = {}] - The source object to create the DocumentResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["line"] = 0;
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DocumentResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DocumentResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DocumentResult(/** @type {Partial<DocumentResult>} */($$parsedSource));
    }
}

export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("sessionID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionID"] = "";
        }
        if (!("agentID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentID"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("archived" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["archived"] = false;
        }
        if (!("entryID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entryID"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("timestamp" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["timestamp"] = "";
        }
        if (!("snippet" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["snippet"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}
