// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as $models from "./models.js";

/**
 * RiskLevel 复用 Permission Domain 的风险枚举。
 * 
 * Tool Registry 只负责为 Capability 标注风险；最终 Allow/Deny/Ask 由 permission.Engine
 * 结合 Agent、Session、参数条件和用户规则计算。使用类型别名避免 Tool 与 Permission 各维护
 * 一套可能漂移的枚举。
 * @typedef {$models.RiskLevel} RiskLevel
 */
