// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";

/**
 * Decision 是前端能够提交的审批动作。
 * 
 * deny 仅拒绝当前 Tool 调用；allow_once 只批准当前 checkpoint 中保存的这一份调用；
 * allow_session 会在当前进程为 Session 创建临时规则；allow_agent 会持久化 Agent Allow Rule；
 * deny_agent 会持久化 Agent Deny Rule，并拒绝当前 ToolCall。第一阶段不提供 Global Scope，
 * 避免权限无意扩散到其他 Agent。
 * @readonly
 * @enum {string}
 */
export const Decision = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DecisionDeny: "deny",
    DecisionDenyAgent: "deny_agent",
    DecisionAllowOnce: "allow_once",
    DecisionAllowSession: "allow_session",
    DecisionAllowAgent: "allow_agent",
};

/**
 * Request 是 Runtime/Frontend 可观察的一次待审批请求。
 * 
 * Request 不保存 raw Tool Arguments；用户可见内容只能来自已经脱敏的 Presentation。
 * CheckpointID/InterruptID 是 Runtime 恢复所需的内部定位信息，对前端 JSON 隐藏。
 */
export class Request {
    /**
     * Creates a new Request instance.
     * @param {Partial<Request>} [$$source = {}] - The source object to create the Request.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("requestId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["requestId"] = "";
        }
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("sessionId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sessionId"] = "";
        }
        if (!("agentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentId"] = "";
        }
        if (!("toolName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["toolName"] = "";
        }
        if (!("risk" in $$source)) {
            /**
             * @member
             * @type {permission$0.RiskLevel}
             */
            this["risk"] = permission$0.RiskLevel.$zero;
        }
        if (!("presentation" in $$source)) {
            /**
             * @member
             * @type {permission$0.Presentation}
             */
            this["presentation"] = (new permission$0.Presentation());
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {Status}
             */
            this["status"] = Status.$zero;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("expiresAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expiresAt"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Request instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Request}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presentation" in $$parsedSource) {
            $$parsedSource["presentation"] = $$createField7_0($$parsedSource["presentation"]);
        }
        return new Request(/** @type {Partial<Request>} */($$parsedSource));
    }
}

/**
 * Status 描述一次 Human Approval 的运行时生命周期。
 * 
 * Approval 不写入 Session Transcript：它属于“运行控制事件”，不是用户或模型消息。
 * Pending 请求只存在当前应用进程；应用退出后 Eino 内存 Checkpoint 一起失效，因此不会
 * 出现重启后自动恢复一个旧的高风险 Tool 调用。长期授权只由 permission.Store 持久化。
 * @readonly
 * @enum {string}
 */
export const Status = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StatusPending: "pending",
    StatusResolving: "resolving",
    StatusResolved: "resolved",
    StatusCancelled: "cancelled",
    StatusExpired: "expired",
};

// Private type creation functions
const $$createType0 = permission$0.Presentation.createFrom;
