// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const Level = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    LevelInfo: "info",
    LevelSuccess: "success",
    LevelWarning: "warning",
    LevelError: "error",
};

/**
 * Notification 是主动助手向宿主桌面发送的统一通知协议。
 * Core 不直接依赖某个操作系统通知 SDK；Desktop Adapter 可以把它投影成
 * Wails 事件、系统通知或应用内 Toast。
 */
export class Notification {
    /**
     * Creates a new Notification instance.
     * @param {Partial<Notification>} [$$source = {}] - The source object to create the Notification.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {Level}
             */
            this["level"] = Level.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("body" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["body"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agentID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["sessionID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["taskID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runID"] = undefined;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Notification instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Notification}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Notification(/** @type {Partial<Notification>} */($$parsedSource));
    }
}
