// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FunctionCall is the function call in a message.
 * It's used in Assistant Message.
 */
export class FunctionCall {
    /**
     * Creates a new FunctionCall instance.
     * @param {Partial<FunctionCall>} [$$source = {}] - The source object to create the FunctionCall.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Name is the name of the function to call, it can be used to identify the specific function.
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Arguments is the arguments to call the function with, in JSON format.
             * @member
             * @type {string | undefined}
             */
            this["arguments"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FunctionCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FunctionCall}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FunctionCall(/** @type {Partial<FunctionCall>} */($$parsedSource));
    }
}

/**
 * ToolCall is the tool call in a message.
 * It's used in Assistant Message when there are tool calls should be made.
 */
export class ToolCall {
    /**
     * Creates a new ToolCall instance.
     * @param {Partial<ToolCall>} [$$source = {}] - The source object to create the ToolCall.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Index is used when there are multiple tool calls in a message.
             * In stream mode, it's used to identify the chunk of the tool call for merging.
             * @member
             * @type {number | null | undefined}
             */
            this["index"] = undefined;
        }
        if (!("id" in $$source)) {
            /**
             * ID is the id of the tool call, it can be used to identify the specific tool call.
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * Type is the type of the tool call, default is "function".
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("function" in $$source)) {
            /**
             * Function is the function call to be made.
             * @member
             * @type {FunctionCall}
             */
            this["function"] = (new FunctionCall());
        }
        if (/** @type {any} */(false)) {
            /**
             * Extra is used to store extra information for the tool call.
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["extra"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolCall instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolCall}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("function" in $$parsedSource) {
            $$parsedSource["function"] = $$createField3_0($$parsedSource["function"]);
        }
        if ("extra" in $$parsedSource) {
            $$parsedSource["extra"] = $$createField4_0($$parsedSource["extra"]);
        }
        return new ToolCall(/** @type {Partial<ToolCall>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = FunctionCall.createFrom;
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
