// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";

/**
 * ApprovalSnapshot 只持久化可安全展示的审批投影，不含 checkpoint、原始 Tool 参数或
 * capability identity。应用重启后对应 Run 会转为 interrupted 并清除此字段。
 */
export class ApprovalSnapshot {
    /**
     * Creates a new ApprovalSnapshot instance.
     * @param {Partial<ApprovalSnapshot>} [$$source = {}] - The source object to create the ApprovalSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("tool_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tool_name"] = "";
        }
        if (!("risk" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["risk"] = "";
        }
        if (!("presentation" in $$source)) {
            /**
             * @member
             * @type {permission$0.Presentation}
             */
            this["presentation"] = (new permission$0.Presentation());
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("expires_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expires_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ApprovalSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ApprovalSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presentation" in $$parsedSource) {
            $$parsedSource["presentation"] = $$createField3_0($$parsedSource["presentation"]);
        }
        return new ApprovalSnapshot(/** @type {Partial<ApprovalSnapshot>} */($$parsedSource));
    }
}

/**
 * ConversationMode 决定 Agent 类型任务在多次运行之间如何使用 Session。
 * 
 * isolated（独立对话）：每个 TaskRun 都创建自己的 Session，运行之间完全隔离。
 * continuous（连续对话）：同一个 Task 的所有运行尽量复用一个持久 Session；如果该
 * Session 被用户手动删除，下次运行会自动创建新的 Session 并更新任务引用。
 * @readonly
 * @enum {string}
 */
export const ConversationMode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConversationIsolated: "isolated",
    ConversationContinuous: "continuous",
};

export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("taskID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["taskID"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runID"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Task | null | undefined}
             */
            this["task"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Run | null | undefined}
             */
            this["run"] = undefined;
        }
        if (!("occurredAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["occurredAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField3_0($$parsedSource["task"]);
        }
        if ("run" in $$parsedSource) {
            $$parsedSource["run"] = $$createField4_0($$parsedSource["run"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ExecutionType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ExecutionAgent: "agent",
    ExecutionNotification: "notification",
};

export class Limits {
    /**
     * Creates a new Limits instance.
     * @param {Partial<Limits>} [$$source = {}] - The source object to create the Limits.
     */
    constructor($$source = {}) {
        if (!("max_duration_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_duration_seconds"] = 0;
        }
        if (!("max_model_calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_model_calls"] = 0;
        }
        if (!("max_tool_calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_tool_calls"] = 0;
        }
        if (!("max_total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_total_tokens"] = 0;
        }
        if (!("max_attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_attempts"] = 0;
        }
        if (!("retry_delay_seconds" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["retry_delay_seconds"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Limits instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Limits}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Limits(/** @type {Partial<Limits>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const MisfirePolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    MisfireSkip: "skip",
    MisfireRunOnce: "run_once",
};

/**
 * @readonly
 * @enum {string}
 */
export const OverlapPolicy = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    OverlapSkip: "skip",
    OverlapQueueOne: "queue_one",
};

export class Run {
    /**
     * Creates a new Run instance.
     * @param {Partial<Run>} [$$source = {}] - The source object to create the Run.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("task_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["task_id"] = "";
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["request_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["runtime_run_id"] = undefined;
        }
        if (!("trigger" in $$source)) {
            /**
             * @member
             * @type {RunTrigger}
             */
            this["trigger"] = RunTrigger.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ExecutionType | undefined}
             */
            this["execution"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parent_run_id"] = undefined;
        }
        if (!("scheduled_for" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scheduled_for"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {RunStatus}
             */
            this["status"] = RunStatus.$zero;
        }
        if (!("tool_calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tool_calls"] = 0;
        }
        if (!("model_calls" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["model_calls"] = 0;
        }
        if (!("input_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["input_tokens"] = 0;
        }
        if (!("output_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["output_tokens"] = 0;
        }
        if (!("total_tokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_tokens"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ApprovalSnapshot | null | undefined}
             */
            this["approval"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result_message_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["result_preview"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["finished_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["deadline_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Run instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Run}
     */
    static createFrom($$source = {}) {
        const $$createField17_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("approval" in $$parsedSource) {
            $$parsedSource["approval"] = $$createField17_0($$parsedSource["approval"]);
        }
        return new Run(/** @type {Partial<Run>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const RunStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RunQueued: "queued",
    RunStarting: "starting",
    RunRunning: "running",
    RunWaitingApproval: "waiting_approval",
    RunSucceeded: "succeeded",
    RunFailed: "failed",
    RunCancelled: "cancelled",
    RunTimedOut: "timed_out",
    RunInterrupted: "interrupted",
    RunSkipped: "skipped",
};

/**
 * @readonly
 * @enum {string}
 */
export const RunTrigger = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TriggerManual: "manual",
    TriggerSchedule: "schedule",
    TriggerRetry: "retry",
    TriggerAutomation: "automation",
};

/**
 * Schedule 是用户可编辑的结构化日程。第一版刻意不暴露原始 Cron，避免时区、DST 和
 * 错过执行语义散落到 UI 字符串中。
 */
export class Schedule {
    /**
     * Creates a new Schedule instance.
     * @param {Partial<Schedule>} [$$source = {}] - The source object to create the Schedule.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ScheduleType}
             */
            this["type"] = ScheduleType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["time_zone"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["run_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["interval_minutes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["time_of_day"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number[] | undefined}
             */
            this["weekdays"] = undefined;
        }
        if (!("misfire_policy" in $$source)) {
            /**
             * @member
             * @type {MisfirePolicy}
             */
            this["misfire_policy"] = MisfirePolicy.$zero;
        }
        if (!("overlap_policy" in $$source)) {
            /**
             * @member
             * @type {OverlapPolicy}
             */
            this["overlap_policy"] = OverlapPolicy.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Schedule instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Schedule}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("weekdays" in $$parsedSource) {
            $$parsedSource["weekdays"] = $$createField5_0($$parsedSource["weekdays"]);
        }
        return new Schedule(/** @type {Partial<Schedule>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ScheduleType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ScheduleManual: "manual",
    ScheduleOnce: "once",
    ScheduleInterval: "interval",
    ScheduleDaily: "daily",
    ScheduleWeekly: "weekly",
};

export class Task {
    /**
     * Creates a new Task instance.
     * @param {Partial<Task>} [$$source = {}] - The source object to create the Task.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("agent_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agent_id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Internal 标识由 Humbert 子系统创建的隐藏任务。它仍然完整持久化并复用
             * Task Runtime，但不会出现在普通用户任务列表中。
             * @member
             * @type {boolean | undefined}
             */
            this["internal"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["origin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["origin_ref"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ExecutionType | undefined}
             */
            this["execution"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ConversationMode 只对 Agent 执行生效。旧任务没有该字段时按 isolated 处理，
             * 保持升级前“每次运行创建新 Session”的行为不变。
             * @member
             * @type {ConversationMode | undefined}
             */
            this["conversation_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * PersistentSessionID 是连续对话当前正在使用的 Session 引用。它是弱引用：
             * Session 可以被用户从会话侧栏独立删除；运行时发现引用失效后会自动创建新会话。
             * @member
             * @type {string | undefined}
             */
            this["persistent_session_id"] = undefined;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {TaskStatus}
             */
            this["status"] = TaskStatus.$zero;
        }
        if (!("schedule" in $$source)) {
            /**
             * @member
             * @type {Schedule}
             */
            this["schedule"] = (new Schedule());
        }
        if (!("limits" in $$source)) {
            /**
             * @member
             * @type {Limits}
             */
            this["limits"] = (new Limits());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["next_run_at"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["archived_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Task instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Task}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType8;
        const $$createField12_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("schedule" in $$parsedSource) {
            $$parsedSource["schedule"] = $$createField11_0($$parsedSource["schedule"]);
        }
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField12_0($$parsedSource["limits"]);
        }
        return new Task(/** @type {Partial<Task>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const TaskStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TaskStatusActive: "active",
    TaskStatusPaused: "paused",
    TaskStatusArchived: "archived",
};

// Private type creation functions
const $$createType0 = permission$0.Presentation.createFrom;
const $$createType1 = Task.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = Run.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ApprovalSnapshot.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = Schedule.createFrom;
const $$createType9 = Limits.createFrom;
