// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * @readonly
 * @enum {string}
 */
export const Action = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ActionIgnore: "ignore",
    ActionNotify: "notify",
    ActionRunAgent: "run_agent",
};

export class Decision {
    /**
     * Creates a new Decision instance.
     * @param {Partial<Decision>} [$$source = {}] - The source object to create the Decision.
     */
    constructor($$source = {}) {
        if (!("action" in $$source)) {
            /**
             * @member
             * @type {Action}
             */
            this["action"] = Action.$zero;
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agent_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["prompt"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Decision instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Decision}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Decision(/** @type {Partial<Decision>} */($$parsedSource));
    }
}

export class Event {
    /**
     * Creates a new Event instance.
     * @param {Partial<Event>} [$$source = {}] - The source object to create the Event.
     */
    constructor($$source = {}) {
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {EventKind}
             */
            this["kind"] = EventKind.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["level"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["agent_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["task_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["run_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["approval_id"] = undefined;
        }
        if (!("occurred_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["occurred_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["metadata"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Event instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Event}
     */
    static createFrom($$source = {}) {
        const $$createField11_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField11_0($$parsedSource["metadata"]);
        }
        return new Event(/** @type {Partial<Event>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const EventKind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    EventTaskFailed: "task_failed",
    EventTaskTimedOut: "task_timed_out",
    EventTaskInterrupted: "task_interrupted",
    EventTaskSucceeded: "task_succeeded",
    EventTaskLongRunningDone: "task_long_running_finished",
    EventTaskWaitingApproval: "task_waiting_approval",
    EventApprovalPending: "approval_pending",
    EventWorkspaceChanged: "workspace_changed",
};

export class PublicEvent {
    /**
     * Creates a new PublicEvent instance.
     * @param {Partial<PublicEvent>} [$$source = {}] - The source object to create the PublicEvent.
     */
    constructor($$source = {}) {
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Record | null | undefined}
             */
            this["record"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Status | null | undefined}
             */
            this["status"] = undefined;
        }
        if (!("occurredAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["occurredAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicEvent instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicEvent}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType2;
        const $$createField2_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField1_0($$parsedSource["record"]);
        }
        if ("status" in $$parsedSource) {
            $$parsedSource["status"] = $$createField2_0($$parsedSource["status"]);
        }
        return new PublicEvent(/** @type {Partial<PublicEvent>} */($$parsedSource));
    }
}

export class Record {
    /**
     * Creates a new Record instance.
     * @param {Partial<Record>} [$$source = {}] - The source object to create the Record.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("event" in $$source)) {
            /**
             * @member
             * @type {Event}
             */
            this["event"] = (new Event());
        }
        if (!("decision" in $$source)) {
            /**
             * @member
             * @type {Decision}
             */
            this["decision"] = (new Decision());
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {RecordStatus}
             */
            this["status"] = RecordStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["automation_task_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["automation_run_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["handled_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Record instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Record}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType5;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("event" in $$parsedSource) {
            $$parsedSource["event"] = $$createField1_0($$parsedSource["event"]);
        }
        if ("decision" in $$parsedSource) {
            $$parsedSource["decision"] = $$createField2_0($$parsedSource["decision"]);
        }
        return new Record(/** @type {Partial<Record>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const RecordStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RecordIgnored: "ignored",
    RecordDeferred: "deferred",
    RecordExecuting: "executing",
    RecordSucceeded: "succeeded",
    RecordFailed: "failed",
};

export class Status {
    /**
     * Creates a new Status instance.
     * @param {Partial<Status>} [$$source = {}] - The source object to create the Status.
     */
    constructor($$source = {}) {
        if (!("running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["running"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_heartbeat_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["next_heartbeat_at"] = undefined;
        }
        if (!("queued_events" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queued_events"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Status}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Status(/** @type {Partial<Status>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Record.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = Status.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = Event.createFrom;
const $$createType6 = Decision.createFrom;
