// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as permission$0 from "../permission/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../tools/models.js";

/**
 * RuntimeServerFailure 表示某个已启用 MCP Server 在当前 Turn 构建真实 Tool 时不可用。
 * 
 * Failure 只属于本 Turn 的能力降级诊断，不会被当成 Runtime 失败终态。Error 已经过
 * logging.RedactText 处理，允许安全暴露给 Desktop UI；真正成功进入 Snapshot 的 Server
 * 仍只存在 Servers 中。
 */
export class RuntimeServerFailure {
    /**
     * Creates a new RuntimeServerFailure instance.
     * @param {Partial<RuntimeServerFailure>} [$$source = {}] - The source object to create the RuntimeServerFailure.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverID"] = "";
        }
        if (!("serverKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverKey"] = "";
        }
        if (!("serverName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverName"] = "";
        }
        if (!("transport" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transport"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeServerFailure instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeServerFailure}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeServerFailure(/** @type {Partial<RuntimeServerFailure>} */($$parsedSource));
    }
}

/**
 * RuntimeSnapshot 是一次 User Turn 冻结的 MCP ToolSet。
 * 
 * Revision 来自 MCP Manager 控制面版本。当前 Turn 创建后，即使 Server 配置或 Agent 选择
 * 发生变化，本 Snapshot 也不会改变。
 */
export class RuntimeServerSnapshot {
    /**
     * Creates a new RuntimeServerSnapshot instance.
     * @param {Partial<RuntimeServerSnapshot>} [$$source = {}] - The source object to create the RuntimeServerSnapshot.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverID"] = "";
        }
        if (!("serverKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverKey"] = "";
        }
        if (!("serverName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverName"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("transport" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["transport"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeServerSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeServerSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeServerSnapshot(/** @type {Partial<RuntimeServerSnapshot>} */($$parsedSource));
    }
}

/**
 * RuntimeToolSnapshot 是 Runtime Audit 使用的最小 MCP Tool 身份，不包含参数或结果。
 */
export class RuntimeToolSnapshot {
    /**
     * Creates a new RuntimeToolSnapshot instance.
     * @param {Partial<RuntimeToolSnapshot>} [$$source = {}] - The source object to create the RuntimeToolSnapshot.
     */
    constructor($$source = {}) {
        if (!("serverID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["serverID"] = "";
        }
        if (!("rawName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rawName"] = "";
        }
        if (!("exposedName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exposedName"] = "";
        }
        if (!("risk" in $$source)) {
            /**
             * @member
             * @type {tools$0.RiskLevel}
             */
            this["risk"] = permission$0.RiskLevel.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeToolSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeToolSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeToolSnapshot(/** @type {Partial<RuntimeToolSnapshot>} */($$parsedSource));
    }
}
