// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Presentation 是一次 Ask 请求的用户可见描述。
 */
export class Presentation {
    /**
     * Creates a new Presentation instance.
     * @param {Partial<Presentation>} [$$source = {}] - The source object to create the Presentation.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {PresentationField[] | undefined}
             */
            this["fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Presentation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Presentation}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField2_0($$parsedSource["fields"]);
        }
        return new Presentation(/** @type {Partial<Presentation>} */($$parsedSource));
    }
}

/**
 * PresentationField 是 Approval UI 可以安全展示的一项参数摘要。
 */
export class PresentationField {
    /**
     * Creates a new PresentationField instance.
     * @param {Partial<PresentationField>} [$$source = {}] - The source object to create the PresentationField.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresentationField instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresentationField}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresentationField(/** @type {Partial<PresentationField>} */($$parsedSource));
    }
}

/**
 * RiskLevel 描述一次 Capability 调用对用户数据和本机环境可能造成的影响。
 * @readonly
 * @enum {string}
 */
export const RiskLevel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    RiskRead: "read",
    RiskWrite: "write",
    RiskExec: "exec",
};

// Private type creation functions
const $$createType0 = PresentationField.createFrom;
const $$createType1 = $Create.Array($$createType0);
