// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Capabilities 是 Runtime 真正使用的有效能力集合。
 */
export class Capabilities {
    /**
     * Creates a new Capabilities instance.
     * @param {Partial<Capabilities>} [$$source = {}] - The source object to create the Capabilities.
     */
    constructor($$source = {}) {
        if (!("tools" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tools"] = false;
        }
        if (!("vision" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["vision"] = false;
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["files"] = false;
        }
        if (!("reasoning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reasoning"] = false;
        }
        if (!("json" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["json"] = false;
        }
        if (!("audio" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["audio"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Capabilities instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Capabilities}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Capabilities(/** @type {Partial<Capabilities>} */($$parsedSource));
    }
}
