// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackupStatus {
    /**
     * Creates a new BackupStatus instance.
     * @param {Partial<BackupStatus>} [$$source = {}] - The source object to create the BackupStatus.
     */
    constructor($$source = {}) {
        if (!("destination" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["destination"] = "";
        }
        if (!("lastError" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastError"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackupStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackupStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackupStatus(/** @type {Partial<BackupStatus>} */($$parsedSource));
    }
}
